SensorsIot/IOTstack

- .templates/mosquitto/filter.acl
- .templates/mosquitto/mosquitto.conf
- .templates/mosquitto/service.yml
Hi. I installed IOTstack recently and ended up making this changes. They are basic and can be useful for security.
This is from: gcgarner#130 Contributor: @Tomasmerca
> Mosquitto changes

- docs/index.md
Removed references to the Wiki (this IS the Wiki).
Fixed typo in EspruinoHub (was EspurinoHub).
Changed "sudo apt-get install git" to "sudo apt install git". My
understanding is that "apt" is considered best practice.
Changed the URL to download the repository from
"https://github.com/gcgarner/IOTstack.git" to
"https://github.com/SensorsIot/IOTstack.git".
Removed the last sentence under "Running under a virtual machine".
Graham closed and unpinned issue 29 so this seems redundant.
Changed several URLs to refer to the new documentation structure.
Added a "Networking" section below "Persistent data" to cover-off the
"first timer" problem of not realising why 127.0.0.1 won't work. It's
such a common problem that I thought it would be better to put it up
front (and thereby explain it twice) …
> Fixes some inconsistencies and makes other tweaks to index page

- README.md
- menu.sh
Add in docker version check on menu startup.
Tested on RPi4
After the first run, I set the major version to be `28` to produce the warning message
> Docker version check

- menu.sh
The url for the supervised HASSIO is changed, because the old one is resulting with error 404 and you cannot finish the installation
This is from: gcgarner#169 Contributor: @peyanski
> update menu.sh for hassio

- .templates/transmission/build.sh
- .templates/transmission/service.yml
- .templates/transmission/volumes.yml
- menu.sh
This PR is to add Transmission container, no more included as plugin into OpenMediaVault 5 release, that uses OMV shared folders.
To make sure the folders are shared between OMV5 and Transmission container, a volume is needed as explained in [approach #2 here](https://stackoverflow.com/a/49952217).
For this reason, it's required the management of new "volumes.yml" file into menu.sh, that can be used by any template, to append all the volume's declaration at the end of docker-compose.yml
Thank you of your awesome job, hope you'll enjoy this PR!
> Transmission container plus volume management

- .templates/deconz/service.yml
- .templates/nodered/build.sh
- menu.sh
Added deCONZ docker image from https://github.com/marthoc/docker-deconz
Also added node-red-contrib-deconz as an option for the Node-RED nodes checklist
Tested on Raspberry Pi 3B and 3B+ with Conbee II, Node-RED (including node-red-contrib-deconz) and Home Assistant.
Hardware (Conbee I/II or Rasbee) must be plugged in when stack is being composed.
Fixes gcgarner#145
> Added deCONZ to stack 

- docs/Grafana.md
Inspired by discussion at [gcgarner/IOTstack/issues/185](https://github.com/gcgarner/IOTstack/issues/185) and [gcgarner/IOTstack/issues/131](https://github.com/gcgarner/IOTstack/issues/131) and similar.
Covers setting the time-zone for the container.
Recommends NOT attempting to change either the admin username or
password via environment variables and explains why. Also includes how
to recover from a lost admin password.
Discusses the how-to of overriding Grafana settings using the example
of enabling anonymous access.
Explains how to establish a "clean slate" state (a bit quicker than
completely deleting and re-installing IOTstack).
> Expansion of Grafana documentation page.

- .templates/grafana/service.yml
Grafana is pinned to version 6.3.6. There is no obvious reason.
I removed the pinning and Grafana advanced to 6.7.3. Some of the
Grafana user interface had moved around (eg the top level contained
a panel for the Grafana blog rather than the list of installed panels)
but things like that are to be expected. There were one or two cosmetic
changes in some of my dashboards (eg font size changes in bar charts)
but the panels all worked out-of-the-box and there was nothing that
suggested any need for caution in removing the pinning to 6.3.6.
> Removes pin of Grafana to version 6.3.6.

- .templates/mosquitto/directoryfix.sh
- .templates/mosquitto/mosquitto.conf
- .templates/mosquitto/service.yml
- docs/Mosquitto.md
Implements changes proposed in issue #68:
1. Add a volume mapping to the template `service.yml`:
```
- ./volumes/mosquitto/pwfile:/mosquitto/pwfile
```
2. Add this line to the template `directoryfix.sh`:
```
sudo mkdir -p ./volumes/mosquitto/pwfile/
```
3. Change the relevant line in the template `mosquitto.conf` to read:
```
#password_file /mosquitto/pwfile/pwfile
```
4. Change the documentation so that the command reads:
```
mosquitto_passwd -c /mosquitto/pwfile/pwfile «MYUSER»
```
Extends Mosquitto documentation to:
* explain logging options
* elaborate on setting up security
* explain how to run Mosquitto as root (rather than user 1883) in
situations where that might be appropriate
Also adds a timestamp format line to the template `mosquitto.conf`:
```
log_timestamp_format …
```
> Mosquitto - make security persistent + extend documentation

- .templates/mosquitto/service.yml
- docs/Mosquitto.md
Following on from issue #67, this PR:
1. Removes the definition of port 9001 from the Mosquitto template;
2. Adds discussion to the Mosquitto documentation explaining how to
support port 9001 *properly,* should the need arise.
> Mosquitto - remove port 9001 from template

- .templates/transmission/build.sh
- .templates/transmission/volumes.yml
Issue #91 described a problem which was traced to three mal-formed path
specifications in the `volumes.yml` template for `transmission`.
The following three lines:
```
device: .volumes/transmission/downloads
device: .volumes/transmission/watch
device: .volumes/transmission/config
```
need to be written as:
```
device: ./volumes/transmission/downloads
device: ./volumes/transmission/watch
device: ./volumes/transmission/config
```
User @ApricotFarm has tested this fix and confirms that it works.
> Correct path specifications in transmission volumes.yml

- .templates/adminer/service.yml
- .templates/blynk_server/service.yml
- .templates/dozzle/service.yml
- .templates/grafana/service.yml
- .templates/influxdb/service.yml
- .templates/mariadb/service.yml
- .templates/mosquitto/service.yml
- .templates/motioneye/service.yml
- .templates/nextcloud/service.yml
- .templates/nodered/service.yml
- .templates/portainer/service.yml
- .templates/postgres/service.yml
- .templates/rtl_433/service.yml
- .templates/tasmoadmin/service.yml
- .templates/timescaledb/service.yml
- .templates/transmission/service.yml
- .templates/webthings_gateway/service.yml
The [Docker Compose file reference](https://docs.docker.com/compose/compose-file/#ports) says:
> When mapping ports in the HOST:CONTAINER format, you may experience
erroneous results when using a container port lower than 60,
because YAML parses numbers in the format xx:yy as a base-60 value.
For this reason, we recommend always explicitly specifying your port
mappings as strings.
This PR adopts the recommendation on all `service.yml` files in the
`.templates` directory. That way, IOTstack uses who work by copying
an existing example will be less likely to strike this problem should
they need to specify a container port less than 60.
I also removed some extraneous blank lines at the ends of `service.yml`
files that were causing sub-optimal layout in `docker-compose.yml`.
> Harmonises service.yml file usage of quote marks around port mappings

- .templates/wireguard/directoryfix.sh
- .templates/wireguard/service.yml
- volumes/wireguard/wg0.conf
This fixes the permissions error described in https://github.com/SensorsIot/IOTstack/issues/126
> Fix wireguard causing permission denied errors

- .templates/gitea/service.yml
kapdap/gitea-rpi has not been updated for two years. kunde21/gitea-arm
is being maintained (most-recent update is 8 weeks ago). I have been
running kunde21/gitea-arm since June and it seems quite stable so I
recommend IOTstack switches to it.
kunde21/gitea-arm also runs as user pi (kapdap/gitea-rpi ran as root):
```
$ ps -C gitea -o euser,ruser,suser,fuser,comm
EUSER    RUSER    SUSER    FUSER    COMMAND
pi       pi       pi       pi       gitea
```
The changes required to service.yml are:
1. Change the image definition to "kunde21/gitea-arm:latest"
2. Add `USER_UID` and `USER_GID` keys to the environment section, each
with the value 1000 (user pi).
> Switch gitea from kapdap/gitea-rpi to kunde21/gitea-arm

- .templates/portainer-ce/directoryfix.sh
- .templates/portainer-ce/service.yml
- docs/Containers/Portainer-ce.md
- docs/Home.md
- menu.sh
This PR proposes supporting Portainer and Portainer CE 2.0 in parallel.
See also [Issue 132](https://github.com/SensorsIot/IOTstack/issues/132).
According to [Portainer documentation]
(https://www.portainer.io/2020/08/portainer-ce-2-0-what-to-expect/):
> Portainer 1.24.x will continue as a separate code branch, released as
> portainer/portainer:latest, and will receive ongoing security updates
> until at least 1st Sept 2021. No new features will be added beyond
> what was available in 1.24.1
The template for Portainer CE:
- Maps external port 9002 to internal port 9000. This is so Portainer CE can coexist with Portainer.
- Maps external port 8000 to internal port 8000. Portainer did not expose port 8000.
[Portainer documentation](https://www.portainer.io/2019/07/how-does-the-edge-agent-wor …
> Adds template and documentation for Portainer-ce

- .templates/mosquitto/terminal.sh
In preparing PR #69 I did not realise that:
```
~/IOTstack/.templates/mosquitto/terminal.sh
```
contained a reference to the `pwfile` with the old (non-persistent)
path. I have changed the text in `terminal.sh` to remove the reference
to the `pwfile` and instead direct the user to the documentation.
The logic is:
* Just changing the path in `terminal.sh` perpetuates the maintenance
problem;
* Most users will only want to set the password once so chucking up the
reminder every time `terminal.sh` is run could become annoying; and
* by reading the documentation, the user would get a better appreciation
for how the password is implemented **and** how to roll it back if
Mosquitto gets into a restart loop.
> Mosquitto - make security persistent + extend documentation - followup

- README.md
- docs/Backups.md
- docs/Containers/EspruinoHub.md
- docs/Getting-Started.md
- docs/index.md
Found all references to gcgarner. Resolved in favour of SensorsIot.
`README.md` instructed users to clone SensorsIot (correct) while `docs/Getting-Started.md` instructed users to clone gcgarner (incorrect).
The gcgarner URL was the reason why several users complained about not receiving updates (see [Issue 132](https://github.com/SensorsIot/IOTstack/issues/132)). Duplicate material is the progenitor of inconsistency so I resolved this by treating `docs/Getting-Started.md` as authoritative, and having `README.md` refer to it.
Ditto other material previously common to both `README.md` and `docs/Getting-Started.md`. It is now all in the latter. A side-effect is to give "Migrating from the old repo?" slightly more prominence. With any luck this will help people who occasionally complain about …
> Docs updates - remove gcgarner references - related improvements

- .templates/blynk_server/Dockerfile
- .templates/blynk_server/directoryfix.sh
- .templates/blynk_server/service.yml
The original version did not create any config files and did not support email.
This commit fixes that, by making use of  `directoryfix.sh` to create the config folder,
which contains two config files, `server.properties` and `mail.properties`.
Note that if they already exist they are not overwritten.
The Dockerfile has been updated to use the latest version 0.41.14,
and a parameter to use a custom `mail.properties`.
`server.properties` should work "as is" for most people, but can be changed as required.
`mail.properties` requires editing to add gmail credentials.
`service.yml` updated to map the configs to the volumes folder.
A new readme guide has been produced which needs adding to the main webpage, this can be found [here](https://gist.github.com/877dev/cfa52044336e1e44d74156ce8b1458aa …
> Update to Blynk local server including config files

- .gitignore
Followup to [Issue 166](https://github.com/SensorsIot/IOTstack/issues/166) to include the following lines in .gitignore:
```
.vscode
*.code-workspace
```
> Add exclusions for Visual Studio Code to IOTstack git ignores

- .templates/telegraf/service.yml
[Issue 163](https://github.com/SensorsIot/IOTstack/issues/163), reported that the template for telegraf did not include:
```
restart: unless-stopped
```
This seems like an oversight.
> Adds restart option for telegraf template

- docs/Getting-Started.md
- menu.sh
- scripts/backup_influxdb.sh
- scripts/docker_backup.sh
- scripts/prune-images.sh
- scripts/prune-volumes.sh
- scripts/restart.sh
- scripts/start.sh
- scripts/stop-all.sh
- scripts/stop.sh
- scripts/update.sh
A recurrent theme on Discord is questions where the underlying cause of the user's problem is an unnecessary use of the sudo command.
To try to reduce the incidence of both the problems and the questions, this PR adds code to the start of most bash scripts. The code checks the EUID and exits with "This script should NOT be run using sudo".
A discussion of the problem of using sudo is also added to docs/Getting-Started.md. Aside from hopefully catching the eye of every new IOTstack user, this will be a useful anchor for Discord questions.
Some scripts also lacked the "hash bang" preamble and I took the opportunity to fix such problems.
> Try to head off problems created by unnecessary use of sudo

- scripts/docker_backup.sh
Dropbox are about to change API versions and discontinue the current API in 2021.
The developer of Dropbox-Uploader has updated the project, it seems for this reason.
The default way the files are saved has been changed, hence this PR is need to fix that.
You will need to create a new dropbox_uploader.sh config file if not already done, ready for
the discontinuation of the old API. https://github.com/andreafabrizi/Dropbox-Uploader
Also updated Dropbox file retention to 30 which is more useful for restoring after an un-noticed issue.
> 2020-12-10-docker_backup.sh folder fix

- .templates/domoticz/service.yml
New menu has moved environment variables from `domoticz.env` into
`service.yml` but the `env_file` reference is still present. This
causes new-menu builds to fail.
> Remove environment file reference from domoticz template

- scripts/python_deps_check.py
`menu.sh` checks whether the dependencies ruamel.yaml and blessed are installed. The script `python_deps_check.py` is used to check the versions of the installed modules. Apparently PyYAML is not a dependency (it's version is not checked), but it's nevertheless imported. If PyYAML is not installed, the script crashes in import error. In this case, `menu.sh` fails to obtain the version number of any of the dependencies, and always prompts the user with a question whether the dependencies should be installed.
This small fix imports only the modules whose version is checked. `menu.sh` will detect the version numbers correctly, even if PyYAML is not installed.
> Fix dependency check, when PyYAML is not installed.

- .templates/heimdall/heimdall.env
- .templates/heimdall/service.yml
"New menu" has not yet moved environment variables from `heimdall.env`
into `service.yml`.
The `env_file` reference is still present in the service definition
but the target file is not being copied into the `./services/heimdall`
directory because there is no `build.py`.
This causes new-menu builds to fail.
> Migrate heimdall environment variables to service definition

- .templates/wireguard/build.sh
Every time you setup your system (menu.sh) the wg0.conf is being replaced by template causing the lost of your previously configuration
> fix wireguard config file being replaced on every setup

- .templates/rtl_433/Dockerfile
- .templates/rtl_433/service.yml
Hello Maintainers,
When trying to use the rtl_433 from within docker, I figured out that the servise must be defined such that it uses the _iotstack_nw_ network, otherwise you cannot send messages to _mosquitto_ (by service name). Furthermore, I suggest to introduce another generic parameter field for the rtl_433 call, which I e.g. use to convert all results to SI units.
Thanks & Best Regards,
Frank
> Bugfix for rtl_433 (docker) needs to run with iotstack_nw network to see mosquitto

- .templates/nextcloud/service.yml
As defined in .templates/mariadb/service.yml the data folder shall be
mounted to /config.
> Correct nextcloud_db data path

- .templates/mosquitto/mosquitto.conf
References:
* [Mosquitto doc](https://mosquitto.org/documentation/migrating-to-2-0/)
* [Workaround](https://github.com/SensorsIot/IOTstack/issues/265)
* [IOTstack new menu breaks Mosquitto configs](https://github.com/SensorsIot/IOTstack/issues/258#issuecomment-772978755)
* [Pull Request on gcgarner/IOTstack](https://github.com/gcgarner/IOTstack/pull/228)
Mosquitto 2.x has introduced a requirement for a `listener` in the
config file. If this is absent, Mosquitto will bind to the loopback
interface. When Mosquitto is running in a container, this implies no
connectivity.
Mosquitto 2.x has also changed the security defaults. Earlier versions
permitted passwordless access out-of-the box. The new version assumes
a password scheme will be implemented and requires passwordless
access to be an …
> Mosquitto 2.x incompatible with default IOTstack config file

- .templates/mosquitto/mosquitto.conf
This is an attempt at proposing a PR to apply to the old-menu branch
to implement the same changes as proposed for the master branch in
[PR266](https://github.com/SensorsIot/IOTstack/pull/266).
> Mosquitto 2.x incompatible with default IOTstack old-menu config file

- .templates/influxdb/service.yml
See:
* [Issue 279](https://github.com/SensorsIot/IOTstack/issues/279)
* [Discord 2021-02-25](https://discord.com/channels/638610460567928832/638610461109256194/814324313754173472)
Those are both from 2021-02-25. It appears that allowing Influx to
update to "latest" results in an error:
```
$ PULL
Pulling influxdb     ... pulling from library/influxdb
ERROR: for influxdb  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```
The solution is to pin to the last known-good version.
> Pin InfluxDB to version 1.8.4 (PR 1 of 2)

- .templates/influxdb/service.yml
See:
* [Issue 279](https://github.com/SensorsIot/IOTstack/issues/279)
* [Discord 2021-02-25](https://discord.com/channels/638610460567928832/638610461109256194/814324313754173472)
Those are both from 2021-02-25. It appears that allowing Influx to
update to "latest" results in an error:
```
$ PULL
Pulling influxdb     ... pulling from library/influxdb
ERROR: for influxdb  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```
The solution is to pin to the last known-good version.
> Pin InfluxDB to version 1.8.4 (PR 2 of 2)

- .templates/mosquitto/directoryfix.sh
- .templates/mosquitto/mosquitto.conf
- .templates/mosquitto/service.yml
Changes `service.yml` to coalesce **file** volume references to
`mosquitto.conf` and `filter.acl` into a single **directory** volume
reference to the `services` directory, and to flag the access as
read-only. See also extended discussion at
[Issue 269](https://github.com/SensorsIot/IOTstack/issues/269).
Changes `mosquitto.conf` to:
1. Improve layout, including grouping like controls.
2. Extend comments on password handling.
3. Fix small typo/bug by removing trailing "/" from
`persistence_location` path (this was showing up in the Mosquitto
log as "//").
Adds checking preamble to `directoryfix.sh` to mitigate two common
mistakes:
1. Prevents invocation from `sudo`; and
2. Warns if the working directory does not appear to be called
"IOTstack".
> Mosquitto service definition - 2 of 2 - old-menu branch

- .templates/blynk_server/Dockerfile
Changes in 0.41.15 are:
Sometimes timer is not removed issue fixed
Dependencies updated
Added property to disable certificate renewal
Fixed NPE in mqtt handler
Added property to support only TLSv1.3 and TLSv1.2
Increased pool size for the DB and getServer command
Fixed OTA after netty libraries updated
> blynk_server dockerfile has been updated to latest version 0.41.15

- .templates/mosquitto/directoryfix.sh
- .templates/mosquitto/mosquitto.conf
- .templates/mosquitto/service.yml
Changes `service.yml` to coalesce **file** volume references to
`mosquitto.conf` and `filter.acl` into a single **directory** volume
reference to the `services` directory, and to flag the access as
read-only. See also extended discussion at
[Issue 269](https://github.com/SensorsIot/IOTstack/issues/269).
Changes `mosquitto.conf` to:
1. Improve layout, including grouping like controls.
2. Extend comments on password handling.
3. Fix small typo/bug by removing trailing "/" from
`persistence_location` path (this was showing up in the Mosquitto
log as "//").
Adds checking preamble to `directoryfix.sh` to mitigate two common
mistakes:
1. Prevents invocation from `sudo`; and
2. Warns if the working directory does not appear to be called
"IOTstack".
> Mosquitto service definition - 1 of 2 - master branch

- .templates/dozzle/service.yml
The [compose specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports)
says:
> Port mapping MUST NOT be used with network_mode: host and doing so
MUST result in a runtime error.
This rule is being enforced by current versions of docker-compose, and
is, in turn causing compose-time errors to appear
(eg [Discord post](https://discord.com/channels/638610460567928832/638610461109256194/825336297828777995)).
This Pull Request resolves the conflict by commenting-out:
* port definitions for dozzle.
Note. Most services that define host mode either omit ports entirely or
already comment them out. This Pull Request is harmonising dozzle.
> Pull Request 2 of 2 (this is for old-menu branch)

- .templates/dozzle/service.yml
- .templates/home_assistant/service.yml
- .templates/homebridge/service.yml
- .templates/openhab/service.yml
- .templates/webthings_gateway/service.yml
The [compose specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports)
says:
> Port mapping MUST NOT be used with network_mode: host and doing so
MUST result in a runtime error.
This rule is being enforced by current versions of docker-compose, and
is, in turn causing compose-time errors to appear
(eg [Discord post](https://discord.com/channels/638610460567928832/638610461109256194/825336297828777995)).
This Pull Request resolves the conflict by commenting-out:
* port definitions for dozzle, homebridge, openhab and
webthings_gateway; and
* the `network_mode: host` directive for home_assistant. Research
suggests that Home Assistant only needs host mode to sniff for
"Amazon Dash" buttons. According to the
[Wikipedia …
> Pull Request 1 of 2 (this is for master branch)

- docs/Accessing-your-Device-from-the-internet.md
- duck/duck.sh
Minor changes to the duckdns script based on [this discussion](https://github.com/SensorsIot/IOTstack/issues/271):
* There's a random delay before the curl command to avoid every client contacting duckdns at the same instance.
* It still sometimes hangs so I think it's good to have the timeout.
* It doesn't write `/var/log/duck.log`. I think it's not needed and requires us to run the script with root privileges. Another option would be to write to some file in home directory.
> Add a random delay before duckdns request

- .templates/zigbee2mqtt/Dockerfile
- .templates/zigbee2mqtt/service.yml
- .templates/zigbee2mqtt_assistant/service.yml
- docs/Containers/Zigbee2MQTT.md
Changes Zigbee2MQTT service definition:
1. Moves container out of host mode.
2. Re-adds port 8080:8080 mapping (web UI).
3. Adds TZ environment variable (to make it clear container supports this).
4. More comments on devices list.
5. Adds new-menu network (iotstack_nw).
6. Builds container from Dockerfile to support sensible IOTstack defaults:
* Referencing Mosquitto by container name rather than localhost
* Enables Zigbee2MQTT web UI by default
7. Expands documentation.
First-time users should only ever have to work out how their adapter presents itself and define it appropriately in the device list.
Dockerfile-based build will not be picked up unless user recreates the service from its template.
Changes to internal default configuration file will not overwrite existing configuration …
> Zigbee2MQTT - IOTstack-friendliness - PR 1 of 2 (master branch)

- .templates/zigbee2mqtt/Dockerfile
- .templates/zigbee2mqtt/service.yml
Changes Zigbee2MQTT service definition:
1. Moves container out of host mode.
2. Re-adds port 8080:8080 mapping (web UI).
3. Adds TZ environment variable (to make it clear container supports this).
4. More comments on devices list.
5. Builds container from Dockerfile to support sensible IOTstack defaults:
* Referencing Mosquitto by container name rather than localhost
* Enables Zigbee2MQTT web UI by default
First-time users should only ever have to work out how their adapter presents itself and define it appropriately in the device list.
Dockerfile-based build will not be picked up unless user recreates the service from its template.
Changes to internal default configuration file will not overwrite existing configuration files. Internal defaults will only become active on first install or …
> Zigbee2MQTT - IOTstack-friendliness - PR 2 of 2 (old-menu branch)

- .templates/blynk_server/Dockerfile
Changes in 0.41.16 are:
Remove obsolete code
Updated dependencies
Fixed map pool size property
> blynk_server dockerfile has been updated to latest version 0.41.16

- .templates/octoprint/service.yml
- docs/Containers/Octoprint.md
Service definition and documentation.
I have been running this for the past 10 days on a Raspberry Pi 3B+
with a standard Raspberry Pi ribbon camera. Apart from being sensitive
to the ordering of operations (eg first switch on the printer, **then**
bring up the container), it just works.
Tests show this installs correctly under new menu without needing
a build.py.
> Adds Octoprint container to new menu (pull request 1 of 2)

- docs/Getting-Started.md
Trying to fix an issue reported on
[Discord](https://discord.com/channels/638610460567928832/638610461109256194/832772736350421012)
where two `sudo apt` commands were being displayed on a single line
in the Wiki.
It might be explained by a spurious tab character.
Only seems to affect the Wiki (GitHub renders correctly).
> Documentation - Getting Started - Wiki rendering problem

- .templates/prometheus/service.yml
- .templates/prometheus/service_cadvisor-arm.yml
- .templates/prometheus/service_node-exporter.yml
Reported in [Issue 320](https://github.com/SensorsIot/IOTstack/issues/320).
`iotstack_nw` definition added to master branch template files:
```
.templates/prometheus/service.yml
.templates/prometheus/service_cadvisor-arm.yml
.templates/prometheus/service_node-exporter.yml
```
> Adds iotstack_nw definition to prometheus containers

- .templates/zigbee2mqtt/Dockerfile
Adds a commented-out "auth_token" field to the default configuration
file set up by the Dockerfile. This follows on from discussion at
[PR310](https://github.com/SensorsIot/IOTstack/pull/310#issuecomment-816557323).
The basic idea is that the web UI should work out-of-the-box but it
should also be easy for anyone who wants to add basic security to
the web interface to do that (or disable the web UI entirely).
Documentation is on master branch on the assumption that most people
read it online.
> Adds web UI password field to Dockerfile - old-menu (2 of 2)

- .templates/zigbee2mqtt/Dockerfile
- docs/Containers/Zigbee2MQTT.md
Adds a commented-out "auth_token" field to the default configuration
file set up by the Dockerfile. This follows on from discussion at
[PR310](https://github.com/SensorsIot/IOTstack/pull/310#issuecomment-816557323).
The basic idea is that the web UI should work out-of-the-box but it
should also be easy for anyone who wants to add basic security to
the web interface to do that (or disable the web UI entirely).
Documentation updated to reflect these changes.
> Adds web UI password field to Dockerfile - master (1 of 2)

- .templates/adguardhome/service.yml
- docs/Containers/AdGuardHome.md
Adds service definition and documentation for AdGuard Home.
I did look, briefly, at the question of a "build.py" file but decided
that that question should be left for someone who understands if or
when it is necessary, and what is needed in it if it is. That someone
is not me. There are several templates that lack a "build.py"
(dashmachine, domoticz, heimdall, homer, portainer_agent, qbittorrent)
so it does not seem to be essential. It shows up in new menu OK. There
are no options that need to be configured in advance.
I made a conscious choice with port 8089 for the admin interface port
**because** it conflicts with PiHole. There are already going to be
other conflicts (eg 53) so this just rams home the point that you
can't run both.
Conversely, a search suggested no conflict with port …
> Adds service definition for AdGuard Home - master (1 of 2)

- mkdocs.yml
The existing mkdocs.yml needs improvement. Currently, it contains:
1. Syntax errors:
* `plugins:` should be at the same level as `theme:`
2. A deprecated directive:
* the `tabs` feature should be expressed as `navigation.tabs`
3. A missing extension required for proper formatting of the IOTstack Wiki:
```
markdown_extensions:
- pymdownx.superfences
```
See [squidfunk/mkdocs-material issues 2639](https://github.com/squidfunk/mkdocs-material/issues/2639).
> Improved mkdocs.yml - old-menu branch - PR 2 of 2

- mkdocs.yml
The existing mkdocs.yml needs improvement. Currently, it contains:
1. Syntax errors:
* `plugins:` should be at the same level as `theme:`
2. A deprecated directive:
* the `tabs` feature should be expressed as `navigation.tabs`
3. A missing extension required for proper formatting of the IOTstack Wiki:
```
markdown_extensions:
- pymdownx.superfences
```
See [squidfunk/mkdocs-material issues 2639](https://github.com/squidfunk/mkdocs-material/issues/2639).
> Improved mkdocs.yml - master branch - PR 1 of 2

- mkdocs.yml
Following on from PRs [335](https://github.com/SensorsIot/IOTstack/pull/335), [336](https://github.com/SensorsIot/IOTstack/pull/336) and [337](https://github.com/SensorsIot/IOTstack/pull/337), it now appears as though the original `mkdocs.yml` contained another error:
```
features:
- tabs
```
Part of the advice from [squidfunk/mkdocs-material issue 2639](https://github.com/squidfunk/mkdocs-material/issues/2639) included that `tabs` had been deprecated in favour of `navigation.tabs` so I made that change in PRs 335 & 336:
```
features:
- navigation.tabs
```
That appears to have had the effect of **activating** the feature, whereas the evidence suggests that the old `tabs` value did not actually activate the feature. The result is that on wider screens, the topic strip which used to appear …
> Remove navigation tabs from docs pages (in favour of topic list)

- docs/Getting-Started.md
Changes:
1. Parenthesis in wrong place.
2. Removed unnecessary "escape" in a title.
3. Added missing command to docker-compose sequence.
4. Added necessary escapes which were being misinterpreted as html.
> Fix typos in getting-started document

- docs/Containers/Home-Assistant.md
Includes:
* [hassio support](https://gist.github.com/Paraphraser/55643bd660db46716f6c81266905cae8#hassio-support-optional) material from old gist; and
* material originally posted as part of [Issue 312](https://github.com/SensorsIot/IOTstack/issues/312), recommended for inclusion by [lole-elol](https://github.com/lole-elol).
Adds how-tos for uninstalling and re-installing Docker as an alternative to rebuilding a Pi if the decision to install hass.io comes after Docker has been installed via IOTstack.
Also tidies-up some formatting and typos.
See also [Closed PR 323](https://github.com/SensorsIot/IOTstack/pull/323).
> Update home assistant documentation

- .templates/nodered/service.yml
Removes default `privileged: true` from `service.yml` in Node-RED master
branch template.
The [Docker documentation](https://docs.docker.com/engine/reference/commandline/run/#full-container-capabilities---privileged)
describes this flag as:
> The --privileged flag gives all capabilities to the container, and it
also lifts all the limitations enforced by the device cgroup controller.
In other words, the container can then do almost everything that the
host can do. This flag exists to allow special use-cases, like running
Docker within Docker.
See also [privileged vs root in Docker](https://www.cloudsavvyit.com/5211/privileged-vs-root-in-docker-whats-the-difference/)
which warns:
> It’s a special flag you can set at runtime specifically to allow a
Docker container to break free from its …
> Node-RED withdraw default privileged flag - PR 1 of 2

- .templates/nodered/service.yml
Removes default `privileged: true` from `service.yml` in Node-RED
old-menu branch template.
The [Docker documentation](https://docs.docker.com/engine/reference/commandline/run/#full-container-capabilities---privileged)
describes this flag as:
> The --privileged flag gives all capabilities to the container, and it
also lifts all the limitations enforced by the device cgroup controller.
In other words, the container can then do almost everything that the
host can do. This flag exists to allow special use-cases, like running
Docker within Docker.
See also [privileged vs root in Docker](https://www.cloudsavvyit.com/5211/privileged-vs-root-in-docker-whats-the-difference/)
which warns:
> It’s a special flag you can set at runtime specifically to allow a
Docker container to break free from its …
> Node-RED withdraw default privileged flag - PR 2 of 2

- .templates/nodered/service.yml
- scripts/nodered_list_installed_nodes.sh
Node-RED revised documentation - PR 2 of 2 - old-menu branch
Adds new volume mapping to nodered service definition to explicitly support ssh for user root inside the container. This does nothing unless and until a user follows the SSH setup instructions in the updated Node-RED container instructions (master branch). This change won't break any existing installations that use the older method.
Adds helper script for finding duplicated nodes to scripts directory.
> Node-RED revised documentation - PR 2 of 2 - old-menu branch

- .templates/influxdb/service.yml
Changes pin from 1.8.4 to 1.8. This will pick up the multiple images tagged with 1.8.5 (following on from multiple images tagged 1.8.4) and any future 1.8.6 etc.
> Pin InfluxDB to 1.8 - PR 1 of 3 - master branch

- .templates/influxdb/service.yml
Changes pin from 1.8.4 to 1.8. This will pick up the multiple images tagged with 1.8.5 (following on from multiple images tagged 1.8.4) and any future 1.8.6 etc.
> Pin InfluxDB to 1.8 - PR 2 of 3 - old-menu branch

- .internal/templates/services/influxdb/config.js
Changes pin from 1.8.4 to 1.8. This will pick up the multiple images tagged with 1.8.5 (following on from multiple images tagged 1.8.4) and any future 1.8.6 etc.
Formatted as per your Discord advice (1.8, 1.8.4, latest).
The problem I see with "latest" is that it doesn't work.
> Pin InfluxDB to 1.8 - PR 3 of 3 - experimental branch

- .templates/octoprint/service.yml
- docs/Containers/Octoprint.md
Removes 9981:8080 port mapping (unnecessary).
Extends documentation:
* first run (Wizard)
* restarting the container
* username and password recovery
> Octoprint - ports - PR 1 of 3 - master branch

- .templates/octoprint/service.yml
Removes 9981:8080 port mapping (unnecessary).
> Octoprint - ports - PR 2 of 3 - old-menu branch

- .internal/templates/services/octoprint/service.yml
Removes 9981:8080 port mapping (unnecessary).
> Octoprint - ports - PR 3 of 3 - experimental branch

- .internal/templates/services/nextcloud/template.yml
Implements consistent service definition across all three branches.
Documentation consolidated into master branch. Includes step-by-step
guide to proper initialisation.
Documentation in old-menu branch reduced to a stub pointing to master
branch.
> Nextcloud - consistent service definition - experimental - 3 of 3

- docs/Getting-Started.md
1. Adds new system patch to update `libseccomp2` to a version that is
compatible with images based on Alpine 3.13 or later.
Any 32-bit Raspbian `zigbee2mqtt` users updating on or about June
3 2021 fell into this hole. The image maintainer reverted to Alpine
3.12 but other Alpine-based images (eg Mosquitto, Node-RED) are at
risk if their maintainers update to 3.13 or later.
References:
- [Alpine 3.13 release notes](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirement)
- [Discord discussion](https://discord.com/channels/638610460567928832/638610461109256194/849960528394059806)
- [Patching options](https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/)
2. Adds words about checking for and resolving "modified" files that
may prevent users …
> Changes to "getting started" documentation - master branch

- .templates/deconz/service.yml
The default tag (:latest) of the deconz docker image uses beta releases
as well. It is probably best to use only stable releases by default and
let users override the tag if they wish to set up beta releases.
> Use a stable build of deconz by default

- .internal/templates/services/openhab/template.yml
- docs/Containers/openHAB.md
Uses a consistent service definition across all three branches.
Removes commented out capabilities which seem unnecessary. These seem
to have been inherited from old-menu. Not present in master branch.
Fixes typo in `EXTRA_JAVA_OPTS` environment variables (no leading quote
mark). Also switches default time-zone to Etc/UTC.
Copy of documentation from master branch.
> openHAB - consistency fixes - experimental branch - 3 of 3

- .templates/openhab/service.yml
- docs/Containers/openHAB.md
Uses a consistent service definition across all three branches.
Removes pin to version 2.4.0. A check today shows "latest" runs on
32-bit Raspbian without problems so there appears to be no reason for
the pin. There is no pin in either master or experimental so this looks
like a legacy holdover.
Fixes mal-formed environment variables (no leading hyphens) so it is
slightly amazing that the resulting docker-compose.yml would work.
Changes to ports 4050 and 4051 to be consistent with master and
experimental branches.
Removes commented out capabilities which seem unnecessary.
Adds logging options from experimental branch.
Replaces documentation with a pointer to master branch.
> openHAB - consistency fixes - old-menu branch - 2 of 3

- .templates/openhab/service.yml
- docs/Containers/openHAB.md
Uses a consistent service definition across all three branches.
Removes commented out ports which seem unnecessary (documented in
environment variables).
Fixes typo in `EXTRA_JAVA_OPTS` environment variables (no leading quote
mark). Also switches default time-zone to Etc/UTC.
Adds logging options from experimental branch.
> openHAB - consistency fixes - master branch - 1 of 3

- docs/Getting-Started.md
1. Clarifies assumption that Raspberry Pi OS is 32-bit version.
2. Adds link to [Issue 375](https://github.com/SensorsIot/IOTstack/issues/375) to record success with IOTstack on Orange Pi WinPlus.
3. Fixes a typo in "starting an individual container".
4. Removes Mosquitto as the example of a non-well-behaved container.
5. Adds a second `docker system prune` to the build scenario.
6. Explains why multiple `prune` commands are sometimes needed.
7. Adds section on version-pinning.
> 20210713 documentation - getting started

- docs/Containers/Node-RED.md
Updates section on Node.js suffixes to reflect the situation with Node-RED version 2.0.x.
> 20210808 documentation - Node-RED

- .templates/mariadb/Dockerfile
- .templates/mariadb/service.yml
- .templates/nextcloud/service.yml
- docs/Containers/MariaDB.md
- docs/Containers/NextCloud.md
1. Adds Dockerfile to MariaDB template to add stability patches recommended in:
* [StackOverflow](https://stackoverflow.com/questions/61809270/how-to-discover-why-mariadb-crashes)
* [Discord](https://discord.com/channels/638610460567928832/638610461109256194/825049573520965703)
Note:
* I have been running these patches for three months and they definitely improve stability (zero crashes in nextcloud_db). The Discord link above contains a similar stability report for MariaDB.
2. Alters service definitions for both MariaDB and Nextcloud to:
* build using the Dockerfile
* add a volume mapping to support backup/restore of MariaDB database.
Note:
* it was a conscious decision to place the db_backup folder in `./volumes/CONTAINER` rather than mimic the arrangement for influxdb. It simplifies …
> 20210809 MariaDB + Nextcloud - master branch - PR 1 of 3

- .templates/mariadb/Dockerfile
- .templates/mariadb/service.yml
- .templates/nextcloud/service.yml
1. Adds Dockerfile to MariaDB template to add stability patches recommended in:
* [StackOverflow](https://stackoverflow.com/questions/61809270/how-to-discover-why-mariadb-crashes)
* [Discord](https://discord.com/channels/638610460567928832/638610461109256194/825049573520965703)
Note:
* I have been running these patches for three months and they definitely improve stability (zero crashes in nextcloud_db). The Discord link above contains a similar stability report for MariaDB.
2. Alters service definitions for both MariaDB and Nextcloud to:
* build using the Dockerfile
* add a volume mapping to support backup/restore of MariaDB database.
Note:
* it was a conscious decision to place the db_backup folder in `./volumes/CONTAINER` rather than mimic the arrangement for influxdb. It simplifies …
> 20210809 MariaDB + Nextcloud - old-menu branch - PR 2 of 3

- .internal/templates/services/mariadb/Dockerfile
- .internal/templates/services/mariadb/template.yml
- .internal/templates/services/nextcloud/template.yml
1. Adds Dockerfile to MariaDB template to add stability patches recommended in:
* [StackOverflow](https://stackoverflow.com/questions/61809270/how-to-discover-why-mariadb-crashes)
* [Discord](https://discord.com/channels/638610460567928832/638610461109256194/825049573520965703)
Note:
* I have been running these patches for three months and they definitely improve stability (zero crashes in nextcloud_db). The Discord link above contains a similar stability report for MariaDB.
2. Alters service definitions for both MariaDB and Nextcloud to:
* build using the Dockerfile
* add a volume mapping to support backup/restore of MariaDB database.
Note:
* it was a conscious decision to place the db_backup folder in `./volumes/CONTAINER` rather than mimic the arrangement for influxdb. It simplifies …
> 20210809 MariaDB + Nextcloud - experimental branch - PR 3 of 3

- .templates/chronograf/service.yml
- .templates/kapacitor/service.yml
- docs/Containers/Chronograf.md
- docs/Containers/Kapacitor.md
1. Adds Chronograf and Kapacitor service definitions to complement Telegraf and InfluxDB, and complete the TICK stack. Assumes Chronograf may be added without Kapacitor (uncommenting relevant lines in Chronograf service definition is required to enable full integration).
2. Adds minimal documentation for both containers.
> 20210826 TICK - master branch - PR 1 of 3

- .internal/templates/services/chronograf/template.yml
- .internal/templates/services/kapacitor/template.yml
Adds Chronograf and Kapacitor service definitions to complement Telegraf and InfluxDB, and complete the TICK stack. Assumes Chronograf may be added without Kapacitor (uncommenting relevant lines in Chronograf service definition is required to enable full integration).
I made no attempt to create matching `build.js` and/or `config.js` scripts.
> 20210826 TICK - experimental branch - PR 3 of 3

- .internal/templates/services/telegraf/buildFiles/Dockerfile
- .internal/templates/services/telegraf/buildFiles/iotstack_defaults/additions/inputs.docker.conf
- .internal/templates/services/telegraf/buildFiles/iotstack_defaults/additions/inputs.mqtt_consumer.conf
- .internal/templates/services/telegraf/template.yml
Changes `telegraf` Dockerfile so that the configuration for sending
metrics to InfluxDB uses the "internal network" URL:
```
http://influxdb:8086
```
On a clean install, Telegraf should communicate with InfluxDB
"out of the box".
Acknowledgement: this problem was discovered by
[Discord user "tablatronix"](https://discord.com/channels/638610460567928832/638610461109256194/898349626179076096)
> 20211015 Telegraf - defaults - experimental branch - PR 3 of 3

- .templates/telegraf/Dockerfile
- .templates/telegraf/iotstack_defaults/additions/inputs.docker.conf
- .templates/telegraf/iotstack_defaults/additions/inputs.mqtt_consumer.conf
- .templates/telegraf/service.yml
Changes `telegraf` Dockerfile so that the configuration for sending
metrics to InfluxDB uses the "internal network" URL:
```
http://influxdb:8086
```
On a clean install, Telegraf should communicate with InfluxDB
"out of the box".
Acknowledgement: this problem was discovered by
[Discord user "tablatronix"](https://discord.com/channels/638610460567928832/638610461109256194/898349626179076096)
> 20211015 Telegraf - defaults - old-menu branch - PR 2 of 3

- .templates/telegraf/Dockerfile
- .templates/telegraf/iotstack_defaults/additions/inputs.docker.conf
- .templates/telegraf/iotstack_defaults/additions/inputs.mqtt_consumer.conf
- .templates/telegraf/service.yml
- docs/Containers/Telegraf.md
Changes `telegraf` Dockerfile so that the configuration for sending
metrics to InfluxDB uses the "internal network" URL:
```
http://influxdb:8086
```
On a clean install, Telegraf should communicate with InfluxDB
"out of the box".
Acknowledgement: this problem was discovered by
[Discord user "tablatronix"](https://discord.com/channels/638610460567928832/638610461109256194/898349626179076096)
> 20211015 Telegraf - defaults - master branch - PR 1 of 3

- docs/Getting-Started.md
The `grep` command for the first recommended system patch uses
un-escaped wildcards. It will always succeed so multiple calls will
keep appending `allow interfaces` to `/etc/dhcpcd.conf`. That doesn't
actually matter but it is untidy.
> 20211015 Getting started documentation

- docs/Containers/NextCloud.md
The `mkdocs` rendering of the NextCloud container documentation page was
not starting a new numbered list item for step 10.
I traced the problem to extraneous tab characters.
Renderings by GitHub (inline) and other engines (MacDown, QLMarkdown)
were correct so this is another example of either `mkdocs` or the
`material` theme being hypersensitive.
> 20211014 NextCloud documentation

- .templates/home_assistant/service.yml
- menu.sh
Adds service definition for `home_assistant` (previously missing).
Changes menu to provide `home_assistant` as an option.
No documentation added (assumes master branch documentation is definitive).
> 20211011 Home Assistant - old-menu branch - PR 2 of 3

- .templates/home_assistant/service.yml
- docs/Containers/Home-Assistant.md
Changes `home_assistant` service definition to:
* Reference ghcr.io containers, and provide options to select tailored
images for Raspberry Pi 3 and 4.
* Places container into Host Mode so it can receive multicast traffic.
Documentation re-organised to clearly separate material relevant to
Hass.io (Home Assistant Core) from Home Assistant Container.
Updates Hass.io material in line with what actually happens when that
version is installed.
> 20211011 Home Assistant - master branch - PR 1 of 3

- docs/Containers/WireGuard.md
The dangers of copy-and-paste, without the "and then check the result" step.
> WireGuard documentation corrections

- .internal/templates/services/mosquitto/buildFiles/Dockerfile
- .internal/templates/services/mosquitto/buildFiles/docker-entrypoint.sh
- .internal/templates/services/mosquitto/buildFiles/iotstack_defaults/config/filter.acl
- .internal/templates/services/mosquitto/buildFiles/iotstack_defaults/config/mosquitto.conf
- .internal/templates/services/mosquitto/buildFiles/iotstack_healthcheck.sh
A problem affecting the build of the Mosquitto container keeps showing
up in Discord questions. Examples:
* [2021-09-17](https://discord.com/channels/638610460567928832/638610461109256194/888096248761045022)
* [2021-09-09](https://discord.com/channels/638610460567928832/638610461109256194/885494986710335498)
The problem is discussed in [alpinelinux/docker-alpine issues/98](https://github.com/alpinelinux/docker-alpine/issues/98).
It is not clear whether:
1. The problem is transient (ie those reporting it are able to get past
the problem on a retry);
2. Only affects Mosquitto or potentially affects other Alpine-based
IOTstack containers using `apk` to add packages (eg Node-RED); or
3. Environmental (eg if there is a proxy system between the Raspberry Pi
and dl-cdn.alpinelinux.org).
This …
> 20210917 Mosquitto - HTTP not HTTPS during build + health check - experimental branch - PR 3 of 3

- .templates/python/Dockerfile
- .templates/python/app/app.py
- .templates/python/build.py
- .templates/python/docker-entrypoint.sh
- .templates/python/service.yml
- docs/Containers/Python.md
Revamps Python structure:
* Dockerfile:
- handles arbitrarily-complex template which defaults to a "hello
world" script and no requirements.txt. The user can later add their own
script, supporting files and requirements.txt as the need arises.
- Only processes requirements.txt if it is present in the template.
- adds docker-entrypoint.sh with self-repair capabilities.
- launches Python script via docker-entrypoint.sh.
* Removes all instances of requirements.txt (was always a null file but,
between old-menu and master branch, seemed to have cloned itself AND
not put one copy where it needed to be).
* Adjusts build.py to copy all template files to services directory.
* Adjusts service definition to:
- take container out of host mode, in favour of providing
commented-out placeholders for …
> 20210908 Python - master branch - PR 1 of 2

- .internal/templates/services/mariadb/buildFiles/Dockerfile
- .internal/templates/services/mariadb/buildFiles/iotstack_healthcheck.sh
Follows on from suggestion in [Issue 415](https://github.com/SensorsIot/IOTstack/issues/415)
to add health-check to more containers. See also
[PR 406](https://github.com/SensorsIot/IOTstack/pull/406/commits/dbb6217ddb7b54e6d6a247a7c2b29ca364482ab5).
Changes:
* Adds `iotstack_healthcheck.sh` script to template.
* Moves Dockerfile into `buildFiles` directory, and adds commands to
copy the health-check script into the local image and activate
health-checking on launch.
Does not change any documentation on experimental branch.
> 20211002 MariaDB health check - experimental branch - PR 3 of 3

- .templates/mariadb/Dockerfile
- .templates/mariadb/iotstack_healthcheck.sh
- docs/Containers/MariaDB.md
Follows on from suggestion in [Issue 415](https://github.com/SensorsIot/IOTstack/issues/415)
to add health-check to more containers. See also
[PR 406](https://github.com/SensorsIot/IOTstack/pull/406/commits/dbb6217ddb7b54e6d6a247a7c2b29ca364482ab5).
Changes:
* Adds `iotstack_healthcheck.sh` script to template.
* Adds commands to Dockerfile to copy that script into the local image
and activate health-checking on launch.
* Reduces old-menu MariaDB documentation to a stub pointing to new-menu
documentation (this is already the situation for old-menu NextCloud
documentation).
> 20211002 MariaDB health check - old-menu branch - PR 2 of 3

- .templates/mariadb/Dockerfile
- .templates/mariadb/iotstack_healthcheck.sh
- docs/Containers/MariaDB.md
- docs/Containers/NextCloud.md
Follows on from suggestion in [Issue 415](https://github.com/SensorsIot/IOTstack/issues/415)
to add health-check to more containers. See also
[PR 406](https://github.com/SensorsIot/IOTstack/pull/406/commits/dbb6217ddb7b54e6d6a247a7c2b29ca364482ab5).
Changes:
* Adds `iotstack_healthcheck.sh` script to template.
* Adds commands to Dockerfile to copy that script into the local image
and activate health-checking on launch.
* Describes health-check functionality in the MariaDB documentation.
* References MariaDB health-check documentation in NextCloud
documentation.
> 20211002 MariaDB health check - master branch - PR 1 of 3

- docs/Getting-Started.md
The `libseccomp2` patch recommended for Raspbian Buster is not needed
for Bullseye (the updated version is already in place).
Installing the patch recommended for Buster breaks Bullseye
installations so it is to be avoided.
Also:
* expands on pre-requisites
* adds note that PiZeroW2 will run IOTstack
* adds style tags (bash, yaml, etc) to code fences
* changes some multi-step commands to use single-step equivalents
(eg `stop` then `rm -rf` replaced with `rm --force --stop -v`)
* rewrites the "nuclear option" to be less destructive while achieving
the same outcome.
> 20211110 adjusts getting-started documentation for Raspbian bullseye

- docs/Containers/NextCloud.md
Changes some multi-step commands to use single-step equivalents
(eg `stop` then `rm -rf` replaced with `rm --force --stop -v`)
> 20211114 NextCloud documentation - backup/restore - simplified commands

- menu.sh
Function `check_git_updates()` does not quote variables used in expressions. This leads to the errors:
```
./menu.sh: line 128: [: f6d9bbd2f702bf4dcb05e285423ba9a8a3f5390c: unary operator expected
./menu.sh: line 130: [: f6d9bbd2f702bf4dcb05e285423ba9a8a3f5390c: unary operator expected
```
Quotes added to expressions.
> 20211116 Menu - master branch - quote variables in expression

- .templates/deconz/service.yml
- .templates/diyhue/service.yml
- .templates/pihole/service.yml
- .templates/telegraf/service.yml
Under 2.x versions of docker-compose, volumes statements in service definitions that have trailing slashes cause:
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist:
```
This problem only shows up on first install of a container (ie when the container's persistent storage area has not yet been initialised).
There are 51 volumes statements across all current service definitions:
```
$ find ~/IOTstack/.templates -name "service.yml" -exec grep -H '\- \./volumes' {} \; | wc -l
51
```
Of those, 5 have a trailing "/" on either or both sides:
```
$ find ~/IOTstack/.templates -name "service.yml" -exec grep -H '\- \./volumes' {} \; | grep -e '/:' -e '/$'
/home/pi/IOTstack/.templates/telegraf/service.yml:    - ./volumes/telegraf/:/etc/telegraf …
```
> 20211116 volume-mounts - master branch - PR 1 of 3

- .templates/deconz/service_conbee.yml
- .templates/deconz/service_conbee_II.yml
- .templates/deconz/service_raspbee.yml
- .templates/diyhue/service.yml
- .templates/pihole/service.yml
- .templates/telegraf/service.yml
Under 2.x versions of docker-compose, volumes statements in service definitions that have trailing slashes cause:
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist:
```
This problem only shows up on first install of a container (ie when the container's persistent storage area has not yet been initialised).
There are 51 volumes statements across all current service definitions:
```
$ find ~/IOTstack/.templates -name "service.yml" -exec grep -H '\- \./volumes' {} \; | wc -l
51
```
Of those, 5 have a trailing "/" on either or both sides:
```
$ find ~/IOTstack/.templates -name "service.yml" -exec grep -H '\- \./volumes' {} \; | grep -e '/:' -e '/$'
/home/pi/IOTstack/.templates/telegraf/service.yml:    - ./volumes/telegraf/:/etc/telegraf …
```
> 20211116 volume-mounts - old-menu branch - PR 2 of 3

- .internal/templates/services/deconz/template.yml
- .internal/templates/services/diyhue/template.yml
- .internal/templates/services/pihole/template.yml
- .internal/templates/services/telegraf/template.yml
Under 2.x versions of docker-compose, volumes statements in service definitions that have trailing slashes cause:
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist:
```
This problem only shows up on first install of a container (ie when the container's persistent storage area has not yet been initialised).
There are 51 volumes statements across all current service definitions:
```
$ find ~/IOTstack/.templates -name "service.yml" -exec grep -H '\- \./volumes' {} \; | wc -l
51
```
Of those, 5 have a trailing "/" on either or both sides:
```
$ find ~/IOTstack/.templates -name "service.yml" -exec grep -H '\- \./volumes' {} \; | grep -e '/:' -e '/$'
/home/pi/IOTstack/.templates/telegraf/service.yml:    - ./volumes/telegraf/:/etc/telegraf …
```
> 20211116 volume-mounts - experimental branch - PR 3 of 3

- .templates/prometheus-cadvisor/service.yml
- .templates/prometheus-nodeexporter/service.yml
- .templates/prometheus/service.yml
- docs/Containers/Prometheus.md
[Issue 472](https://github.com/SensorsIot/IOTstack/issues/472) reports a new-menu problem where selecting Prometheus does not install cadvisor and nodeexporter.
The template `service.yml` for Prometheus contains all three service definitions. It is not clear why cadvisor and nodeexporter are being removed prior to their insertion into the compose file.
> NextCloud and NextCloud_DB are both defined in a single `service.yml`. Both services make it into the compose file so a working pattern exists for this basic approach.
Prior to [PR419](https://github.com/SensorsIot/IOTstack/pull/419), the template contained `build.sh`, `service_cadvisor-arm.yml` and `service_node-exporter.yml` as well as `service.yml`. That was not working under new-menu, possibly explained by the following line in …
> 20220117 prometheus - master branch

- .internal/templates/services/mosquitto/buildFiles/docker-entrypoint.sh
Following a suggestion from @ukkopahis, this pull request proposes logging self-repair activities.
Guard messages make it clear when self-repair begins and ends:
```
[IOTstack] begin self-repair
…
[IOTstack] end self-repair
```
Between the guard messages:
* `-v` option added to `rsync`
* `-c` option added to `chown`
These cause the respective processes to log any changes they make to persistent storage.
Example. Assume `config/filter.acl` has been deleted and ownership of the `pwfile` folder and its contents has been changed to "pi:pi". Self-repair needs to restore `filter.acl` and restore the ownership to "1883:1883":
```
[IOTstack] begin self-repair
sending incremental file list
./
config/
config/filter.acl
pwfile/
sent 326 bytes  received 50 bytes  752.00 bytes/sec
total size is 1,077 …
```
> 20211220 mosquitto-selfRepair-logging - experimental branch - PR 3 of 3

- .templates/mosquitto/docker-entrypoint.sh
Following a suggestion from @ukkopahis, this pull request proposes logging self-repair activities.
Guard messages make it clear when self-repair begins and ends:
```
[IOTstack] begin self-repair
…
[IOTstack] end self-repair
```
Between the guard messages:
* `-v` option added to `rsync`
* `-c` option added to `chown`
These cause the respective processes to log any changes they make to persistent storage.
Example. Assume `config/filter.acl` has been deleted and ownership of the `pwfile` folder and its contents has been changed to "pi:pi". Self-repair needs to restore `filter.acl` and restore the ownership to "1883:1883":
```
[IOTstack] begin self-repair
sending incremental file list
./
config/
config/filter.acl
pwfile/
sent 326 bytes  received 50 bytes  752.00 bytes/sec
total size is 1,077 …
```
> 20211220 mosquitto-selfRepair-logging - old-menu branch - PR 2 of 3

- .templates/mosquitto/docker-entrypoint.sh
Following a suggestion from @ukkopahis, this pull request proposes logging self-repair activities.
Guard messages make it clear when self-repair begins and ends:
```
[IOTstack] begin self-repair
…
[IOTstack] end self-repair
```
Between the guard messages:
* `-v` option added to `rsync`
* `-c` option added to `chown`
These cause the respective processes to log any changes they make to persistent storage.
Example. Assume `config/filter.acl` has been deleted and ownership of the `pwfile` folder and its contents has been changed to "pi:pi". Self-repair needs to restore `filter.acl` and restore the ownership to "1883:1883":
```
[IOTstack] begin self-repair
sending incremental file list
./
config/
config/filter.acl
pwfile/
sent 326 bytes  received 50 bytes  752.00 bytes/sec
total size is 1,077 …
```
> 20211220 mosquitto-selfRepair-logging - master branch - PR 1 of 3

- .internal/templates/services/nextcloud/template.yml
Pull Requests [PR387](https://github.com/SensorsIot/IOTstack/pull/387), [PR388](https://github.com/SensorsIot/IOTstack/pull/388), [PR389](https://github.com/SensorsIot/IOTstack/pull/389) added a port mapping of `9322:3306` to facilitate backup and restores - so the routines could determine when the MariaDB service was ready for business.
The need for this was superseded by PRs [416](https://github.com/SensorsIot/IOTstack/pull/416), [417](https://github.com/SensorsIot/IOTstack/pull/417) and [418](https://github.com/SensorsIot/IOTstack/pull/418). It is sufficient for backup and restore routines to run the health check and rely on the return status.
This PR removes the `9322:3306` as no longer needed. It will also avoid the need to protect the port with an iptables rule in situations where …
> 20211215 nextcloud_db - exposed port - experimental branch - PR 3 of 3

- .templates/nextcloud/service.yml
Pull Requests [PR387](https://github.com/SensorsIot/IOTstack/pull/387), [PR388](https://github.com/SensorsIot/IOTstack/pull/388), [PR389](https://github.com/SensorsIot/IOTstack/pull/389) added a port mapping of `9322:3306` to facilitate backup and restores - so the routines could determine when the MariaDB service was ready for business.
The need for this was superseded by PRs [416](https://github.com/SensorsIot/IOTstack/pull/416), [417](https://github.com/SensorsIot/IOTstack/pull/417) and [418](https://github.com/SensorsIot/IOTstack/pull/418). It is sufficient for backup and restore routines to run the health check and rely on the return status.
This PR removes the `9322:3306` as no longer needed. It will also avoid the need to protect the port with an iptables rule in situations where …
> 20211215 nextcloud_db - exposed port - old-menu branch - PR 2 of 3

- .templates/nextcloud/service.yml
- docs/Containers/NextCloud.md
Pull Requests [PR387](https://github.com/SensorsIot/IOTstack/pull/387), [PR388](https://github.com/SensorsIot/IOTstack/pull/388), [PR389](https://github.com/SensorsIot/IOTstack/pull/389) added a port mapping of `9322:3306` to facilitate backup and restores - so the routines could determine when the MariaDB service was ready for business.
The need for this was superseded by PRs [416](https://github.com/SensorsIot/IOTstack/pull/416), [417](https://github.com/SensorsIot/IOTstack/pull/417) and [418](https://github.com/SensorsIot/IOTstack/pull/418). It is sufficient for backup and restore routines to run the health check and rely on the return status.
This PR removes the `9322:3306` as no longer needed. It will also avoid the need to protect the port with an iptables rule in situations where …
> 20211215 nextcloud_db - exposed port - master branch - PR 1 of 3

- docs/Containers/Blynk_server.md
- docs/Containers/Mosquitto.md
- docs/Containers/NextCloud.md
- docs/Containers/Node-RED.md
- docs/Containers/Telegraf.md
- docs/Containers/Zigbee2MQTT.md
Documentation updated to make it clear that the visibility of both a local and base image in `docker images` and Portainer depends on the version of docker-compose. Modern docker-compose only shows the local image so only a single "prune" is needed when a local image is rebuilt atop a newly-updated base image from DockerHub.
Affects documentation for Blynk Server, Mosquitto, NextCloud, Node-RED, Telegraf and Zigbee2MQTT. Prometheus documentation already updated in [PR487](https://github.com/SensorsIot/IOTstack/pull/487).
> 20220206 documentation - master branch

- .templates/prometheus/service.yml
Uses `prometheus-` prefix consistently for subordinate containers (service name, container name, dependency name) to address concern raised in comment to [Issue 472](https://github.com/SensorsIot/IOTstack/issues/472#issuecomment-1030104238).
> 20220206 prometheus - old-menu branch - PR 2 of 2

- .templates/prometheus-cadvisor/service.yml
- .templates/prometheus-nodeexporter/service.yml
- .templates/prometheus/service.yml
- docs/Containers/Prometheus.md
Uses `prometheus-` prefix consistently for subordinate containers (service name, container name, dependency name) to address concern raised in comment to [Issue 472](https://github.com/SensorsIot/IOTstack/issues/472#issuecomment-1030104238).
Documentation updated.
Fixes #472
> 20220206 prometheus - master branch - PR 1 of 2

- install.sh
- menu.sh
- scripts/deps/version_check.py
A docker version like 20.10.5+dfsg1 wasn't recognized. Now strips all '+' and '-' postfixes.
Fixes #447
Fixes #496
> Fix docker version parsing

- .templates/influxdb/terminal.sh
It's useful to give command line parameters to influxdb like this:
.templates/influxdb/terminal.sh -precision rfc3339
This change just gives parameters on to the influx command.
> Allow cli parameters to be given

- .github/workflows/main.yml
Limits *action* access to just the repository that the action is run by.
As recommended by:
https://docs.github.com/en/actions/security-guides/automatic-token-authentication
Tested to work in my fork on github.
> use GITHUB_TOKEN for better security

- docs/Basic_setup/Custom.md
- docs/Basic_setup/Networking.md
- docs/Containers/Adminer.md
- docs/Containers/Chronograf.md
- docs/Containers/Kapacitor.md
- docs/Containers/Node-RED.md
- docs/Containers/Octoprint.md
- docs/Containers/Python.md
- docs/Containers/Telegraf.md
- docs/Developers/BuildStack-RandomPassword.md
- docs/Developers/BuildStack-Services.md
Add code-block highlight type (mostly yaml) to code blocks missing them (and not added in any other pull-request).
> docs: add missing code highligt types

- docs/Backups.md.old
- docs/Basic_setup/Accessing-your-Device-from-the-internet.md
- docs/Basic_setup/What-is-sudo.md
- docs/Basic_setup/index.md
- docs/Containers/Chronograf.md
- docs/Containers/Kapacitor.md
- docs/Containers/MariaDB.md
- docs/Containers/Node-RED.md
- docs/Containers/Octoprint.md
- docs/Containers/OpenHab.md
- docs/Containers/Prometheus.md
- docs/Containers/Python.md
- docs/Containers/RTL_433-docker.md
- docs/Containers/Telegraf.md
- docs/Containers/WireGuard.md
- docs/Updates/gcgarner-migration.md
- docs/javascript/fix-codeblock-console-copy-button.js
- docs/style.css
- mkdocs.yml
Use the correct `console` highlighting for shell-session code-blocks and prevent user-selection of the leading `$` and lines representing the command output. Do this in order to help the end-user to just copy just the relevant commands to be executed.
* update code blocks where there are both commands and output to use the `console` highlighting.
* prevent user from selecting the leading $ or the command output
making it easier to copy-paste just all the commands. Done using css. Screenshot of how selection skips unwanted parts:
* fix the copy button to only copy the user-selectable parts of the code-block. Done with javascript.
> docs: Console code-block highlighting

- .internal/templates/services/zigbee2mqtt/Dockerfile
- .internal/templates/services/zigbee2mqtt/template.yml
Deprecates Dockerfile-based build in favour of environment variables
that implement the same behaviour.
Dockerfile retained to avoid introducing a breaking change. A
notification is displayed each time the Dockerfile is run:
```
*** DEPRECATION NOTICE: Please read IOTstack Zigbee2MQTT documentation:
*** https://sensorsiot.github.io/IOTstack/Containers/Zigbee2MQTT/
```
The intention is that user attention will be drawn to the need to update
their service definitions.
The revised service definition:
* includes a `depends_on` clause tying Zigbee2MQTT to Mosquitto (the
default arrangement for IOTstack).
* reduces the `devices` list to just `- /dev/ttyAMA0:/dev/ttyACM0`
in favour of extended "how to" documentation for device discovery.
Addresses issues raised in #402, #423 and #538. …
> 20220404 Zigbee2MQTT - experimental branch - PR 3 of 3

- .templates/zigbee2mqtt/Dockerfile
- .templates/zigbee2mqtt/service.yml
- docs/Containers/Zigbee2MQTT.md
Deprecates Dockerfile-based build in favour of environment variables
that implement the same behaviour.
Dockerfile retained to avoid introducing a breaking change. A
notification is displayed each time the Dockerfile is run:
```
*** DEPRECATION NOTICE: Please read IOTstack Zigbee2MQTT documentation:
*** https://sensorsiot.github.io/IOTstack/Containers/Zigbee2MQTT/
```
The intention is that user attention will be drawn to the need to update
their service definitions.
The revised service definition:
* includes a `depends_on` clause tying Zigbee2MQTT to Mosquitto (the
default arrangement for IOTstack).
* reduces the `devices` list to just `- /dev/ttyAMA0:/dev/ttyACM0`
in favour of extended "how to" documentation for device discovery.
Addresses issues raised in #402, #423 and #538. …
> 20220404 Zigbee2MQTT - old-menu branch - PR 2 of 3

- .templates/zigbee2mqtt/Dockerfile
- .templates/zigbee2mqtt/service.yml
- docs/Containers/Zigbee2MQTT.md
Deprecates Dockerfile-based build in favour of environment variables
that implement the same behaviour.
Dockerfile retained to avoid introducing a breaking change. A
notification is displayed each time the Dockerfile is run:
```
*** DEPRECATION NOTICE: Please read IOTstack Zigbee2MQTT documentation:
*** https://sensorsiot.github.io/IOTstack/Containers/Zigbee2MQTT/
```
The intention is that user attention will be drawn to the need to update
their service definitions.
The revised service definition:
* includes a `depends_on` clause tying Zigbee2MQTT to Mosquitto (the
default arrangement for IOTstack).
* reduces the `devices` list to just `- /dev/ttyAMA0:/dev/ttyACM0`
in favour of extended "how to" documentation for device discovery.
Addresses issues raised in #402, #423 and #538. …
> 20220404 Zigbee2MQTT - master branch - PR 1 of 3

- docs/Containers/WireGuard.md
Fixes some spacing and alignment errors (apparent in MacDown authoring
tool).
> 20220327 WireGuard documentation

- docs/Containers/Telegraf.md
> 20220327 Telegraf documentation

- docs/Containers/Prometheus.md
> 20220327 Prometheus documentation

- docs/Containers/Portainer-ce.md
> 20220327 Portainer-CE documentation

- docs/Containers/Pi-hole.md
Reduces PiHole documentation to a stub, pointing to master branch
documentation.
> 20220327 PiHole - old-menu branch - PR 2 of 2

- docs/Containers/MariaDB.md
> 20220327 MariaDB documentation

- docs/Containers/Home-Assistant.md
Fixes some spacing and alignment errors (apparent in MacDown authoring
tool).
Prefers multi-line command syntax over `&&` form which can be confusing
to new users (quasi standard followed in other IOTstack documentation).
Prefers `$ ` prompt form for commands users should execute. This is
another quasi-standard.
Explicitly sets `cd ~/IOTstack` where its omission might produce
unexpected results.
Adds code-fence rendering hints where appropriate.
> 20220327 Home Assistant documentation

- docs/Containers/Blynk_server.md
> 20220327 Blynk Server documentation

- docs/Containers/AdGuardHome.md
> 20220327 AdGuardHome documentation

- docs/Containers/Node-RED.md
Fixes internal hyperlink problems discovered while discussing #521.
Adds "stackoverflow" style anchors to each title. Tested by running
through MacDown-to-HTML-to-BBEdit link checker. No broken links as of
this commit.
`mkdocs` still uses auto-generated anchors. Those will always work
because they depend on the actual headings at the moment of generation.
It is only internal cross-references that can fracture if too much
reliance is place on auto-generated anchors plus an assumption that
titles will either never change or that authors will be cognisant of
the need to re-validate internal anchors BY HAND.
> 20220324 Node-RED docs - master branch

- .templates/mosquitto/Dockerfile
- .templates/mosquitto/service.yml
Changed Dockerfile and default service definition to support
`MOSQUITTO_BASE` argument which defaults to `eclipse-mosquitto:latest`.
This means users will not have to edit `.templates/mosquitto/Dockerfile`
in order to pin to a specific version.
Also added image metadata fields (`build-args` and `based-on`) and
unset environment variables not needed outside Dockerfile scope.
> 20220323 mosquitto - old-menu branch - PR 2 of 2

- .templates/mosquitto/Dockerfile
- .templates/mosquitto/service.yml
- docs/Containers/Mosquitto.md
Changed Dockerfile and default service definition to support
`MOSQUITTO_BASE` argument which defaults to `eclipse-mosquitto:latest`.
This means users will not have to edit `.templates/mosquitto/Dockerfile`
in order to pin to a specific version.
Also added image metadata fields (`build-args` and `based-on`) and
unset environment variables not needed outside Dockerfile scope.
Documentation updated to explain new structure and how to pin.
> 20220323 mosquitto - master branch - PR 1 of 2

- docs/Basic_setup/index.md
- docs/Updates/index.md
The recent network change breaks the stack for existing users, requiring
manual fixes.
Add links to doc pages where Discord users have reportedly looked for
solutions, without finding the right place.
Closes #490
> docs: Add more warnings about the breaking network change

- docs/Containers/Grafana.md
* Fix documentation to work with new-menu/master-branch
* Adds how to change config with old-menu
* Simplify documentation while trying to retain most of the information
content. Add links to upstream documentation for details.
> grafana: Fix outdated documentation

- .templates/mosquitto/iotstack_defaults/config/mosquitto.conf
- docs/Containers/Mosquitto.md
* Connection messages may cause unnecessary flash wear
* Fix docs to be precise about how docker log persistence
> mosquitto: disable connection_message logging

- .templates/influxdb2/service.yml
- menu.sh
Adds InfluxDB 2 container. Documentation on Master branch.
`menu.sh` changes:
1. Adds InfluxDB 2 to menu.
2. Removes problematic if-test, renames `armhf_keys` array to `keylist`,
removes `sys_arch` declaration. Rationale:
- Original code fragments:
```
declare -a armhf_keys=(
...
)
sys_arch=$(uname -m)
```
```
if [ $(echo "$sys_arch" | grep -c "arm") ]; then
keylist=("${armhf_keys[@]}")
else
echo "your architecture is not supported yet"
exit
fi
```
- Analysis:
1. The if test always succeeds because it is testing the
exit-code of `grep` rather than the value returned by the
`-c` option.
2. This explains why the old menu has been working when
`uname -m` returns "aarch64" on Pis with a 64-bit kernel (if
not necessarily a 64-bit user mode).
It also explains why old-menu works on macOS with …
> 20220602 InfluxDB 2 - old-menu branch - PR 2 of 3

- .internal/templates/services/grafana/template.yml
- .internal/templates/services/influxdb/template.yml
Adds health-check functionality to Grafana and InfluxDB 1.8, as
discussed in #415.
Health-check functionality already added to Mosquitto via #408.
Closes #415
> 20220517 Grafana InfluxDB HealthCheck - experimental branch - PR 3 of 3

- .templates/grafana/service.yml
- .templates/influxdb/service.yml
Adds health-check functionality to Grafana and InfluxDB 1.8, as
discussed in #415.
Health-check functionality already added to Mosquitto via #407.
Closes #415
> 20220517 Grafana InfluxDB HealthCheck - old-menu branch - PR 2 of 3

- README.md
- docs/Basic_setup/index.md
- docs/Updates/Changelog.md
- docs/Updates/index.md
- docs/Updates/migration-network-change.md
- mkdocs.yml
Collection of purely documentation improvements:
* docs/Updates
* Add how to do Raspberry OS "apt update"
* Change full update procedure to recreate from templates
* Clarify wording
* docs: autoselect initial color-scheme. If user has browser with dark-mode preference, automatically select it.
* docs/Getting Started: Small fixes and improvments
* Reword volume-mount section for better clarity
* Fix scripted install section to link to PiBuilder (was linking to deprecated gist)
* Convert "patch 2" steps to numbered list for better readability
* docs: add changelog
* docs: move network migration to its own page
> Doc improvements

- docs/Containers/AdGuardHome.md
- docs/Containers/Blynk_server.md
- docs/Containers/Home-Assistant.md
- docs/Containers/MariaDB.md
- docs/Containers/Mosquitto.md
- docs/Containers/NextCloud.md
- docs/Containers/Node-RED.md
- docs/Containers/Pi-hole.md
- docs/Containers/Portainer-ce.md
- docs/Containers/Prometheus.md
- docs/Containers/Python.md
- docs/Containers/Telegraf.md
- docs/Containers/WireGuard.md
- docs/Containers/Zigbee2MQTT.md
- mkdocs.yml
See reasoning from #558
Change mostly done by command:
`git grep -l '# <a name=' -- docs | xargs -n 1 sed -i -E 's%(#* )<a name="?(.*)"?></a>(.*)%\1\3 { #\2 }%'`
Also a removal of redundant section with its link placed at a more logical place.
Closes #558
> Docs: Refactor to define anchors using attribute list

- docs/index.md
- mkdocs.yml
- requirements-mkdocs.txt
Preview available at my fork: https://ukkopahis.github.io/IOTstack/
Resolves #520
Makes the page a bit tall, but that's an acceptable compromise:
> docs/Home: add full site page listing

- .internal/templates/services/domoticz/template.yml
A Discord thread starting at
https://discord.com/channels/638610460567928832/638610461109256194/1005812386688680006
revealed that the Domoticz would not function properly on a clean
install. The symptom was either a 400 or a 404 error, depending on the
URL.
Three issues identified with existing service definition:
1. Wrong image base. Should be "lscr.io/linuxserver/domoticz".
2. Wrong image tag. Should be "latest".
3. `network_mode: bridge`.
It has never been clear what `network_mode: bridge` is intended to do.
It is the only container with this option. While it may once have been
needed, its presence now appears to prevent the container from
responding correctly on port 8083.
> 20220810 domoticz - experimental branch - PR 3 of 3

- .templates/domoticz/domoticz.env
- .templates/domoticz/service.yml
- docs/Containers/Domoticz.md
A Discord thread starting at
https://discord.com/channels/638610460567928832/638610461109256194/1005812386688680006
revealed that the Domoticz would not function properly on a clean
install. The symptom was either a 400 or a 404 error, depending on the
URL.
Three issues identified with existing service definition:
1. Wrong image base. Should be "lscr.io/linuxserver/domoticz".
2. Wrong image tag. Should be "latest".
3. `network_mode: bridge`.
It has never been clear what `network_mode: bridge` is intended to do.
It is the only container with this option. While it may once have been
needed, its presence now appears to prevent the container from
responding correctly on port 8083.
No IOTstack documentation exists for this container. A related PR adds
basic documentation. This PR adds a stub …
> 20220810 domoticz - old-menu branch - PR 2 of 3

- .templates/domoticz/service.yml
- docs/Containers/Domoticz.md
A Discord thread starting at
https://discord.com/channels/638610460567928832/638610461109256194/1005812386688680006
revealed that the Domoticz would not function properly on a clean
install. The symptom was either a 400 or a 404 error, depending on the
URL.
Three issues identified with existing service definition:
1. Wrong image base. Should be "lscr.io/linuxserver/domoticz".
2. Wrong image tag. Should be "latest".
3. `network_mode: bridge`.
It has never been clear what `network_mode: bridge` is intended to do.
It is the only container with this option. While it may once have been
needed, its presence now appears to prevent the container from
responding correctly on port 8083.
No IOTstack documentation exists for this container. This PR adds some
basic documentation in the form of …
> 20220810 domoticz - master branch - PR 1 of 3

- .templates/nodered/build.sh
- .templates/nodered/service.yml
- scripts/nodered_list_installed_nodes.sh
Adopts build-argument syntax in template service definition.
In `build.sh`:
* Harmonises list of add-on nodes (and default on/off states) to be
consistent with master branch.
* Constructs Dockerfile header as a "here" document to make future
maintenance easier. Identical to `Dockerfile.template` on master branch.
All documentation on master branch.
> 20220708 Node-RED - old-menu branch - PR 2 of 2

- .templates/nodered/Dockerfile.template
- .templates/nodered/service.yml
- docs/Containers/Node-RED.md
- scripts/nodered_list_installed_nodes.sh
Adopts build-argument syntax in the template service definition +
template Dockerfile to pass an image tag plus an optional list of
extra packages to the Dockerfile at build time.
Pinning to a specific base image can now be accomplished in the Compose
file. This places Node-RED on equal footing with containers that do not
use local Dockerfiles (and Mosquitto which already has similar
build-argument syntax).
Together, the changes mean user customisations to the first part of the
Dockerfile are no longer at risk of being overwritten by menu runs to
change the list of add-on nodes.
For any given IOTstack installation, there is some possibility of a
hybrid result, depending on how and when the user runs the menu, or
which techniques each user employs to manage their Compose file and
Node-RED …
> 20220708 Node-RED - master branch - PR 1 of 2

- docs/Updates/Changelog.md
- docs/index.md
Update the Changelog page to reflect previous changes and currently open pull-requests.
Preview available at: https://ukkopahis.github.io/IOTstack/Updates/Changelog/
Also add Changlog link to the Wiki homepage.
Other contributors are welcome to make [change suggestions](https://github.com/ukkopahis/IOTstack/edit/doc-changelog/docs/Updates/Changelog.md) to the Changelog after creating a pull request.
Using this pull-request to close old resolved/abandoned issues:
* Empty / Not actionable
* Closes #374
* Closes #288
* Closes #111
* Duplicate of issue mentioned in comment
* Closes #410
* Closes #164
* Discussion seems to be over
* Closes #448
* Closes #86
* Closes #47
* Closes #41
* No way to reproduce the pi-hole runaway log flood
* Closes #508
* User support provided / issue resolved 
* …
> docs/Changelog: update to reflect latest changes

- .bash_aliases
- docs/Basic_setup/Docker.md
- mkdocs.yml
* fix aliases to work regardless of user's current directory (using the'-f' flag instead of changing the directory would ignore a possibly existing `docker-compose.override.yml')
* fix iotstack_build alias to include "--pull --no-cache", as without these there may be cases where everything isn't fully updated.
* add the iotstack_update_docker_images alias to perform the basic container update
* docs/Docker: reword for clarity & typo fixes
> .bash_aliases: auto-remove orphan containers

- .templates/telegraf/service.yml
If no hostname is set, telegraf will generate a new random one each time it is recreated. It's more beginner and user-friendly to have a persistent non-changing hostname.
The hostname is used for tagging data sent to influxdb. If you have multiple stacks sending measurements to the same influx, this should be changed on at least one of the stacks. But that's expert usage, and not nearly as relevant as the single-stack case. Having many lots of different tagged hostnames may also reduce performance.
Note: this commit was previously part of https://github.com/SensorsIot/IOTstack/pull/554, but now split into a separate PR, as no-one shouldn't object to this being merged. (as opposed to the dependency-removal)
> Telegraf: report 'iotstack' as hostname to influx

- .templates/telegraf/iotstack_defaults/auto_include/inputs.docker.conf
- docs/Containers/Telegraf.md
* Fix default configuration not to use deprecated options (causing warnings in logs). Fixes #556
* Fix small documentation errors
Note: these commits were previously part of #554, but now split into a separate PR, as no-one shouldn't object to them being merged. (as opposed to the dependency-removal)
> Telegraf: fix deprecated options and doc typos

- docs/Containers/InfluxDB.md
Fixes the problem reported by #599.
This is an unfortunate, predictable and predicted side-effect of moving from this style of anchored title:
```
```
to this style:
```
```
The former style is testable by generating HTML from the Markdown and running it through a validator. The latter style isn't amenable to that approach because anchor generation is done "just in time" by mkdocs. Until we find some way to test mkdocs output in a systematic way, fairly trivial semantic errors (like the missing "#" in this case) will occasionally slip through the cracks.
Also fixed another broken link (`#authWarning`).
Fixes #599.
> 20220913 Influx documentation - master branch

- .internal/templates/services/prometheus/buildFiles/iotstack_defaults/config.yml
Per issue #620, the default `config.yml` should reference:
- `prometheus-cadvisor:8080` not `cadvisor:8080`
- `prometheus-nodeexporter:9100` not `nodeexporter:9100`
> 2022-11-08 Prometheus defaults - experimental branch - PR 3 of 3

- .templates/prometheus/iotstack_defaults/config.yml
Per issue #620, the default `config.yml` should reference:
- `prometheus-cadvisor:8080` not `cadvisor:8080`
- `prometheus-nodeexporter:9100` not `nodeexporter:9100`
> 2022-11-08 Prometheus defaults - old-menu branch - PR 2 of 3

- .templates/prometheus/iotstack_defaults/config.yml
- docs/Containers/Prometheus.md
Per issue #620, the default `config.yml` should reference:
- `prometheus-cadvisor:8080` not `cadvisor:8080`
- `prometheus-nodeexporter:9100` not `nodeexporter:9100`
Master branch doco updated to add migration tips.
Fixes #620
> 2022-11-08 Prometheus defaults - master branch - PR 1 of 3

- .internal/templates/services/tasmoadmin/template.yml
`raymondmm/tasmoadmin` on DockerHub was last updated two years ago.
Switches image to `ghcr.io/tasmoadmin/tasmoadmin:latest`.
Also adds `TZ` to template.
Removes reference to `iotstack_nw`.
> 2022-10-28 tasmoadmin - experimental branch - PR 3 of 3

- docs/Basic_setup/Troubleshooting.md
- docs/Basic_setup/index.md
Getting Started:
* Expands on PiBuilder option
* Explains purpose of dhcpcd patch
Troubleshooting:
* Adds section on device errors (eg ttyAMA0 not present on non-Pi hardware)
* Adds section on system freezes. Primarily aimed at misbehaving SSDs. Includes trying USB2 port, checking dhcpcd patch is in place, and adding quirks string for some SSDs.
Touches-up some miscellaneous layout issues noted in passing.
> 2022-10-28 basics documentation - master branch

- scripts/nodered_version_check.sh
Adds `nodered_version_check.sh` script to scripts folder (previously available via
[gist](https://gist.github.com/Paraphraser/c8939213faf2de8a10f2a1f67452b0c1#-useful-script-nodered_version_check-)).
Documentation added to master branch.
> 2022-10-11 Node-RED version-check script - old-menu branch - PR 2 of 3

- docs/Containers/Node-RED.md
- scripts/nodered_version_check.sh
Adds `nodered_version_check.sh` script to scripts folder (previously available via
[gist](https://gist.github.com/Paraphraser/c8939213faf2de8a10f2a1f67452b0c1#-useful-script-nodered_version_check-)).
Adds documentation to Node-RED wiki page.
> 2022-10-11 Node-RED version-check script - master branch - PR 1 of 3

- .templates/wireguard/service.yml
- scripts/2022-10-01-wireguard-restructure.sh
WireGuard has started renaming the `custom-services.d` and `custom-cont-init.d` directories to have random suffixes, along with the following README.txt:
```
********************************************************
********************************************************
*                                                      *
*                         !!!!                         *
* Custom scripts or services found in legacy locations *
*                         !!!!                         *
*    Please move your custom scripts and services      *
*    to /custom-cont-init.d and /custom-services.d     *
*    respectively to ensure they continue working.     *
*                                                      *
*  Visit https://linuxserver.io/custom for more info.  *
* …
```
> 2022-10-01 WireGuard volumes restructure - old-menu branch - PR 2 of 3

- .templates/wireguard/service.yml
- docs/Containers/WireGuard.md
- scripts/2022-10-01-wireguard-restructure.sh
WireGuard has started renaming the `custom-services.d` and `custom-cont-init.d` directories to have random suffixes, along with the following README.txt:
```
********************************************************
********************************************************
*                                                      *
*                         !!!!                         *
* Custom scripts or services found in legacy locations *
*                         !!!!                         *
*    Please move your custom scripts and services      *
*    to /custom-cont-init.d and /custom-services.d     *
*    respectively to ensure they continue working.     *
*                                                      *
*  Visit https://linuxserver.io/custom for more info.  *
* …
```
> 2022-10-01 WireGuard volumes restructure - master branch - PR 1 of 3

- docs/Containers/InfluxDB2.md
Fix typo in example - container should be referenced as `influxdb2`
across the internal bridged network.
> 2022-09-25 InfluxDB2 - master branch

- docs/Containers/Zigbee2MQTT.md
Clarify what happens if the container starts with the default device
`/dev/ttyAMA0` in the service definition. The process probes the device,
finds it doesn't respond like a Zigbee adapter, and aborts without
starting the web GUI. Because of the `restart: unless-stopped` clause,
Docker restarts the container and the same sequence repeats. 
> 2022-09-25 Zigbee2MQTT - master branch

- .templates/tasmoadmin/service.yml
`raymondmm/tasmoadmin` on DockerHub was last updated two years ago.
Switches image to `ghcr.io/tasmoadmin/tasmoadmin:latest`.
Also adds `TZ` to template.
> 2022-10-28 tasmoadmin - old-menu branch - PR 2 of 3

- .templates/homer/service.yml
Updated template to latest defaults and recommendations, including:
- Added initial assets env variable so the service won't error out for first time users (like me)
- Changed user id & group id to use docker user function (see below explanation)
I discovered that the Homer wouldn't start with the default template as it had no assets defined. Adding the INIT_ASSETS env variable fixed this, but had permissions errors. In v2022.02.2 the method of assigning UID and GID was changed to user the docker user option (and not env var). These changes are discussed in [Homer Issue 441](https://github.com/bastienwirtz/homer/issues/441) and [Homer Issue 459](https://github.com/bastienwirtz/homer/issues/459), and [Homer's troubleshooting page](https://github.com/bastienwirtz/homer/blob/main/docs/trouble …
> Homer: Fix Template

- docs/Basic_setup/Default-Configs.md
Noticed dash machine was not listed in default-configs.md while I was looking to add changedection.io to IOTstack. We should capture that port 5000 has been used.
> Update Default-Configs.md - add dashmachine

- .templates/pihole/pihole.env
- .templates/pihole/service.yml
See #648 for background to this PR.
Consequential changes:
* harmonises template service definition by removing reference to port 443 but does not re-align other entries (did not seem worthwhile).
* harmonises default environment variables file so it is identical to the inline environment variables on master branch. This includes new-style TZ syntax and comments directing users to IOTstack wiki doco on the admin password, and Pi-hole doco on supported environment variables.
> 2023-01-22 Pi-hole admin password changes - old-menu branch - PR 2 of 3

- .internal/templates/services/pihole/config.js
- .internal/templates/services/pihole/template.yml
…3 of 3
See #648 for background to this PR.
Consequential changes:
* harmonises template service definition by removing reference to port 443 and re-aligning entries.
* harmonises default environment variables to be the same as master branch (including comments).
* removes obsolete `networks:` clause.
* removes handling for `TZ`, `WEBPASSWORD`, `DNS1` and `DNS2` from the modifiable environment. The DNS pair are a consequence of overall harmonisation.
> 2023-01-22 Pi-hole admin password changes - experimental branch - PR 3 of 3

- .templates/portainer_agent/service.yml
> 2023-01-29 portainer_agent - master branch

- .templates/syncthing/service.yml
Realigned. Also takes opportunity to:
* Adopt `TZ=${TZ:-Etc/UTC}`
* Adopt `x-ports:` clause to document ports in use for host-mode container.
> 2023-01-29 syncthing - master branch

- .templates/qbittorrent/service.yml
> 2023-01-29 qbittorrent - master branch

- .templates/duckdns/service.yml
> 2023-01-29 duckdns - master branch

- .internal/templates/services/pgadmin4/template.yml
- .internal/templates/services/postgres/template.yml
1. Adds pgAdmin4:
- service definition
2. Consequential changes to PostgreSQL container:
- Adopted modern syntax for environment variables (`.env` support).
- Removed obsolete `iotstack_nw` definition.
- Added volume path for backup folder to support IOTstackBackup.
> 2023-02-07 pgadmin4 - experimental branch

- .templates/mariadb/Dockerfile
Adjusts Dockerfile to cope with rename of internal file path `/defaults/my.cnf` to `/defaults/custom.cnf`.
Strategy is to check for the presence of both files and then apply the stability patches to the first match. This should mean that the Dockerfile is backwards compatible with images that use `my.cnf`.
Fixes #664
> 2023-02-14 MariaDB Dockerfile - master branch - PR 1 of 3

- .templates/mariadb/Dockerfile
Adjusts Dockerfile to cope with rename of internal file path `/defaults/my.cnf` to `/defaults/custom.cnf`.
Strategy is to check for the presence of both files and then apply the stability patches to the first match. This should mean that the Dockerfile is backwards compatible with images that use `my.cnf`.
> 2023-02-14 MariaDB Dockerfile - old-menu branch - PR 2 of 3

- .internal/templates/services/mariadb/buildFiles/Dockerfile
Adjusts Dockerfile to cope with rename of internal file path `/defaults/my.cnf` to `/defaults/custom.cnf`.
Strategy is to check for the presence of both files and then apply the stability patches to the first match. This should mean that the Dockerfile is backwards compatible with images that use `my.cnf`.
> 2023-02-14 MariaDB Dockerfile - experimental branch - PR 3 of 3

- .templates/timescaledb/service.yml
> 2023-01-29 timescaledb - master branch

- .templates/blynk_server/service.yml
- docs/Containers/Blynk_server.md
Changes external HTTPS port for Blynk Server from 9443 to 9444.
This is a consequence of PR #671 claiming 9443 for Portainer-CE.
Documentation updated.
> 2023-03-09 Blynk-server https port - master branch - PR 1 of 3

- .templates/blynk_server/service.yml
- .templates/portainer-ce/service.yml
Changes external HTTPS port for Blynk Server from 9443 to 9444.
This is a consequence of PR #671 claiming 9443 for Portainer-CE.
Also adds external port 9443 to Portainer-CE on old-menu branch to keep this branch in sync with  the master branch changes made via #671.
> 2023-03-09 Blynk-server https port - old-menu branch - PR 2 of 3

- .internal/templates/services/blynk_server/template.yml
- .internal/templates/services/portainer_ce/template.yml
Changes external HTTPS port for Blynk Server from 9443 to 9444.
This is a consequence of PR #671 claiming 9443 for Portainer-CE.
Also adds external port 9443 to Portainer-CE on old-menu branch to keep this branch in sync with  the master branch changes made via #671.
> 2023-03-09 Blynk-server https port - experimental branch - PR 3 of 3

- .templates/zerotier-client/service.yml
- .templates/zerotier-router/service.yml
- docs/Containers/ZeroTier.md
Corrects a major brain-fade problem created in #595. Implements correct IOTstack-compliant service definitions for:
* ZeroTier client
* ZeroTier router
Documentation:
* adapts YAML line numbers to new service definition
* fixes missing `/0` CIDR notation in definition of default route
* adds section on enabling full tunnelling for remote clients in Topology 4
* adds explanation about host mode and `x-ports` syntax (an issue which can surface if an obsolete version of docker-compose is being used).
> 2023-03-29 ZeroTier - master branch - PR 1 of 2

- .templates/zerotier-client/service.yml
- .templates/zerotier-router/service.yml
Corrects a major brain-fade problem created in #596. Implements correct IOTstack-compliant service definitions for:
* ZeroTier client
* ZeroTier router
> 2023-03-29 ZeroTier - old-menu branch - PR 2 of 2

- .templates/nodered/service.yml
- docs/Containers/Node-RED.md
Background:
Changes:
1. Removes Bluetooth-specific volumes and devices from template.
2. Updates TZ to `TZ=${TZ:-Etc/UTC}` syntax.
3. Realigns build arguments (yamllint).
4. Adds documentation to Node-RED wiki page (master branch) to explain how to re-add volumes and devices if Bluetooth support is required on a Raspberry Pi:
- This means Node-RED will launch successfully on non-Pi hardware.
- Documentation references `/dev/serial1` rather than `/dev/ttyAMA0`.
> 2023-05-15 Node-RED adaptation to expected kernel change - master branch - PR 1 of 3

- .templates/deconz/hardware_list.yml
- .templates/deconz/service.yml
- docs/Containers/Deconz.md
Background:
Changes:
1. Replaces `ttyAMA0` with `serial0` in master path list.
2. Realigns comment and multiple trailing blank lines (yamllint).
3. Documentation adjusted to cater for both menu situations.
> 2023-05-15 deCONZ adaptation to expected kernel change - master branch - PR 1 of 2

- .templates/deconz/service_conbee.yml
- .templates/deconz/service_conbee_II.yml
- .templates/deconz/service_raspbee.yml
- docs/Containers/deconz.md
Background:
Changes:
1. Adopts generic syntax for device specification to prompt user to add the relevant key (`DECONZ_DEVICE_PATH`) and path (eg `/dev/serial0`) to `.env`. Example:
```
$ echo DECONZ_DEVICE_PATH=/dev/serial0 >>~/IOTstack/.env
```
2. Reduces documentation to a stub pointing to the deCONZ page of the IOTstack Wiki.
> 2023-05-15 deCONZ adaptation to expected kernel change - old-menu branch - PR 2 of 2

- .templates/wireguard/service.yml
- docs/Containers/WireGuard.md
Brings service definition into line with
[linuxserver.io recommendations](https://github.com/linuxserver/docker-wireguard/pkgs/container/wireguard#usage).
Changes:
1. Corrects YAML "errors" identified by `yamllint`.
3. Removes `/lib/modules` volume mapping (per linuxserver.io)
4. Removes `SYS_MODULE` capability (per linuxserver.io)
> 2023-05-16 Wireguard conformance - master branch - PR 1 of 2

- .templates/wireguard/service.yml
Brings service definition into line with
[linuxserver.io recommendations](https://github.com/linuxserver/docker-wireguard/pkgs/container/wireguard#usage).
Changes:
1. Corrects YAML "errors" identified by `yamllint`.
3. Removes `/lib/modules` volume mapping (per linuxserver.io)
4. Removes `SYS_MODULE` capability (per linuxserver.io)
> 2023-05-16 Wireguard conformance - old-menu branch - PR 2 of 2

- .templates/home_assistant/service.yml
- docs/Containers/Home-Assistant.md
Background:
- [Home Assistant documentation](https://www.home-assistant.io/installation/raspberrypi#docker-compose)
Changes:
1. Removes Bluetooth-specific volumes and devices from template.
2. Removes Pi-hardware-specific image options (still available but no longer mentioned in the Home Assistant documentation; and not relevant where IOTstack may be deployed on non-Pi hardware).
3. Adds documentation to Home Assistant wiki page (master branch) to explain how to re-add volumes and devices if Bluetooth support is required on a Raspberry Pi:
- This means Home Assistant will launch successfully on non-Pi hardware.
- Documentation references `/dev/serial1` rather than `/dev/ttyAMA0` as the external device but maintains the latter as the internal …
> 2023-05-16 Home Assistant adaptation to expected kernel change - master branch - PR 1 of 2

- .templates/home_assistant/service.yml
Background:
- [Home Assistant documentation](https://www.home-assistant.io/installation/raspberrypi#docker-compose)
Changes:
1. Removes Bluetooth-specific volumes and devices from template.
2. Removes hardware-specific image options (still available but no longer mentioned in the Home Assistant documentation; and not relevant where IOTstack may be deployed on non-Pi hardware).
3. Adds privileged flag (present on master branch and specified in the Home Assistant documentation).
> 2023-05-16 Home Assistant adaptation to expected kernel change - old-menu branch - PR 2 of 2

- .templates/octoprint/service.yml
Background:
Changes:
1. Adopts generic syntax for device specification to prompt user to add the relevant key (`OCTOPRINT_DEVICE_PATH`) and path (eg `/dev/ttyUDB0`) to `.env`. Example:
```
$ echo OCTOPRINT_DEVICE_PATH=/dev/ttyUSB0 >>~/IOTstack/.env
```
3. Corrects YAML "errors" identified by `yamllint`.
> 2023-05-16 OctoPrint adaptation to expected kernel change - old-menu branch - PR 2 of 2

- .templates/zigbee2mqtt/service.yml
- docs/Containers/Zigbee2MQTT.md
Background:
Changes:
1. Adopts generic syntax for device specification to prompt user to add the relevant key (`ZIGBEE2MQTT_DEVICE_PATH`) and path (eg `/dev/ttyUSB0`) to `.env`. Example:
```
$ echo ZIGBEE2MQTT_DEVICE_PATH=/dev/ttyUSB0 >>~/IOTstack/.env
```
3. Adds (disabled) environment variable to enable debugging.
4. Rewrites documentation to explain the how-to of device-path setup.
> 2023-05-16 Zigbee2MQTT adaptation to expected kernel change - master branch - PR 1 of 2

- .templates/zigbee2mqtt/service.yml
Background:
Changes:
1. Adopts generic syntax for device specification to prompt user to add the relevant key (`ZIGBEE2MQTT_DEVICE_PATH`) and path (eg `/dev/ttyUSB0`) to `.env`. Example:
```
$ echo ZIGBEE2MQTT_DEVICE_PATH=/dev/ttyUSB0 >>~/IOTstack/.env
```
3. Adds (disabled) environment variable to enable debugging.
> 2023-05-16 Zigbee2MQTT adaptation to expected kernel change - old-menu branch - PR 2 of 2

- .templates/motioneye/service.yml
- docs/Containers/MotionEye.md
Service definition:
1. Switches to DockerHub image that is actively being maintained (`ccrisan` hasn't been updated in two years; `dontobi` is current).
2. Adjusts timezone mechanism from `/etc/localtime` map to `TZ` support.
3. Changes streaming port for first camera to 8766, assuming that additional cameras will take 8767, 8768 and so on. There is more scope for expansion in this range than in 808x where there are numerous possibilities for collision.
Updates documentation:
1. Adds current references for both MotionEye and Motion.
2. Explains external:internal association of streaming ports.
3. Discusses clip storage issues, including alternative storage location.
> 2023-06-14 MotionEye - master branch - PR 1 of 2

- .templates/adguardhome/service.yml
- .templates/chronograf/service.yml
- .templates/diyhue/service.yml
- .templates/docker-compose-base.yml
- .templates/dozzle/service.yml
- .templates/duckdns/service.yml
- .templates/kapacitor/service.yml
- .templates/mosquitto/service.yml
- .templates/n8n/service.yml
- .templates/openhab/service.yml
- .templates/pgadmin4/service.yml
- .templates/portainer_agent/service.yml
- .templates/postgres/service.yml
- .templates/python/service.yml
- .templates/qbittorrent/service.yml
- .templates/ring-mqtt/service.yml
- .templates/rtl_433/service.yml
- .templates/scrypted/service.yml
- .templates/syncthing/service.yml
- .templates/telegraf/service.yml
- .templates/timescaledb/service.yml
- .templates/webthingsio_gateway/service.yml
- .templates/zerotier-client/service.yml
- .templates/zerotier-router/service.yml
- .yamllint.yaml
Applies changes recommended by `yamllint`, subject to the following alterations to the default ruleset:
```yml
---
extends: default
rules:
empty-lines:
max: 2
max-start: 0
max-end: 1
line-length:
max: 200
```
Opportunistic changes:
- adopt `TZ=${TZ:-Etc/UTC}`:
- `adguardhome`
- `chronograf`
- `kapacitor`
- `mosquitto`
- `n8n`
- `ring-mqtt`
- `rtl_433`
- `telegraf`
- wrap port specs in quotes:
- `ring-mqtt`
- `syncthing`
- `timescaledb`
- adopt `x-ports` syntax:
- `python`
- `webthingsio_gateway`
Also changes `docker-compose-base.yml` to prepend triple-hyphen YAML marker.
> 2023-06-14 yamllint - master branch - PR 1 of 2

- .templates/adguardhome/service.yml
- .templates/chronograf/service.yml
- .templates/diyhue/service.yml
- .templates/dozzle/service.yml
- .templates/kapacitor/service.yml
- .templates/mosquitto/service.yml
- .templates/openhab/service.yml
- .templates/pgadmin4/service.yml
- .templates/plex/service.yml
- .templates/python/service.yml
- .templates/ring-mqtt/service.yml
- .templates/webthings_gateway/service.yml
- .templates/zerotier-client/service.yml
- .templates/zerotier-router/service.yml
- .yamllint.yaml
- menu.sh
Applies changes recommended by `yamllint`, subject to the following alterations to the default ruleset:
```yml
---
extends: default
rules:
empty-lines:
max: 2
max-start: 0
max-end: 1
line-length:
max: 200
```
Opportunistic changes:
- adopt `TZ=${TZ:-Etc/UTC}`:
- `adguardhome'
- `chronograf`
- `dozzle`
- `kapacitor`
- `mosquitto`
- `python`
- `ring-mqtt`
- wrap port specs in quotes:
- `ring-mqtt`
- `webthings_gateway`
- adopt `x-ports` syntax:
- `python`
- `webthings_gateway`
- replace commented-out `logging` clause with `x-logging`
- `openhab`
- Switch `webthings_gateway` from `/dev/ttyACM0` to prompt-style replacement for `/dev/serial0`.
Also changes `menu.sh` to prepend triple-hyphen YAML marker when generating the compose file.
> 2023-06-14 yamllint - old-menu branch - PR 2 of 2

- .templates/pihole/pihole.env
- .templates/pihole/service.yml
Applies changes recommended by `yamllint`.
Adds `FTLCONF_MAXDBDAYS` to the template environment file with the existing default of 365 days. Master branch documentation explains its use.
Adds `PIHOLE_DNS_` to the template environment file with the existing defaults of 8.8.8.8 and 8.8.4.4. Master branch documentation explains its use.
> 2023-06-15 Pi-hole - old-menu branch - PR 2 of 2

- .templates/telegraf/Dockerfile
- .templates/telegraf/entrypoint.sh
- .templates/telegraf/iotstack_defaults/auto_include/outputs.influxdb.conf
Issue reported on
[Discord](https://discord.com/channels/638610460567928832/638610461109256194/1121820918210121838) led to the discovery of several problems with Telegraf:
1. Default configuration had been amended to:
- Add support for both InfluxDB 1.8 and InfluxDB 2; and
- Comment-out both InfluxDB outputs.
The practical consequences were:
- The Dockerfile `sed` command could not find `[outputs.influxdb]`, so the `urls = ["http://influxdb:8086"]` could not be inserted, so telegraf could not write to any database; and
- The container went into a restart loop.
2. The default `entrypoint.sh` script had been amended to invoke telegraf via:
```
exec setpriv --reuid telegraf --init-groups "$@"
```
Inside the container, user "telegraf" is userID 999. Outside
container space, user 999 is not a …
> 2023-06-24 Telegraf - master branch - PR 1 of 2

- .templates/telegraf/Dockerfile
- .templates/telegraf/entrypoint.sh
- .templates/telegraf/iotstack_defaults/auto_include/inputs.cpu_temp.conf
- .templates/telegraf/iotstack_defaults/auto_include/inputs.docker.conf
- .templates/telegraf/iotstack_defaults/auto_include/outputs.influxdb.conf
Issue reported on
[Discord](https://discord.com/channels/638610460567928832/638610461109256194/1121820918210121838) led to the discovery of several problems with Telegraf:
1. Default configuration had been amended to:
- Add support for both InfluxDB 1.8 and InfluxDB 2; and
- Comment-out both InfluxDB outputs.
The practical consequences were:
- The Dockerfile `sed` command could not find `[outputs.influxdb]`, so the `urls = ["http://influxdb:8086"]` could not be inserted, so telegraf could not write to any database; and
- The container went into a restart loop.
2. The default `entrypoint.sh` script had been amended to invoke telegraf via:
```
exec setpriv --reuid telegraf --init-groups "$@"
```
Inside the container, user "telegraf" is userID 999. Outside
container space, user 999 is not a …
> 2023-06-24 Telegraf - old-menu branch - PR 2 of 2

- .internal/templates/services/nodered/buildFiles/addons.json
Pins `node-red-node-serialport` to version `0.15.0`. This seems to be the only version that works with current Node-RED (3.0.2).
Test case showing version `0.15.0` working included with #681. Also includes links to related issues on other repositories which led to this solution.
> 2023-04-09 Node-RED pin serial node - experimental branch - PR 3 of 3

- .templates/nodered/build.sh
Pins `node-red-node-serialport` to version `0.15.0`. This seems to be the only version that works with current Node-RED (3.0.2).
Test case showing version `0.15.0` working included with #681. Also includes links to related issues on other repositories which led to this solution.
> 2023-04-09 Node-RED pin serial node - old-menu branch - PR 2 of 3

- .templates/nodered/addons.yml
Pins `node-red-node-serialport` to version `0.15.0`. This seems to be the only version that works with current Node-RED (3.0.2).
Test case showing version `0.15.0` working included with #681. Also includes links to related issues on other repositories which led to this solution.
Fixes #681.
> 2023-04-09 Node-RED pin serial node - master branch - PR 1 of 3

- .templates/octoprint/service.yml
- docs/Containers/Octoprint.md
Background:
Changes:
1. Adopts generic syntax for device specification to prompt user to add the relevant key (`OCTOPRINT_DEVICE_PATH`) and path (eg `/dev/ttyUDB0`) to `.env`. Example:
```
$ echo OCTOPRINT_DEVICE_PATH=/dev/ttyUSB0 >>~/IOTstack/.env
```
3. Corrects YAML "errors" identified by `yamllint`.
4. Rewrites documentation to explain the how-to of device-path setup in various situations.
> 2023-05-16 OctoPrint adaptation to expected kernel change - master branch - PR 1 of 2

- .templates/homebridge/service.yml
Change from oznu to homebridge. New version is available only on homebridge.
https://github.com/homebridge/docker-homebridge
> Important Update
> We have moved the hosting of the offical homebridge docker image from oznu/homebridge to homebridge/homebridge. Please update your environments as needed to pickup the latest image.
> 2023-08-08 Update service.yml for Homebridge

- .templates/mosquitto/docker-entrypoint.sh
The folder structure for a newly-created or self-repaired persistent store assumes ownership of id 1883 (which is "mosquitto" inside the container) and file/folder modes copied from the `iotstack_defaults` folder hierarchy.
Investigations during #731 revealed that Mosquitto now wants the password file to be owned by root with a mode of 600.
Although the mode requirement could be accommodated by changing the `iotstack_defaults` structure, the ownership requirement can't be met that way.
This fix adds the necessary `chown` and `chmod` commands to the entry-point script.
> 2023-10-09 Mosquitto entry-point script - master branch - PR 1 of 2

- .templates/mosquitto/docker-entrypoint.sh
The folder structure for a newly-created or self-repaired persistent store assumes ownership of id 1883 (which is "mosquitto" inside the container) and file/folder modes copied from the `iotstack_defaults` folder hierarchy.
Investigations during #731 revealed that Mosquitto now wants the password file to be owned by root with a mode of 600.
Although the mode requirement could be accommodated by changing the `iotstack_defaults` structure, the ownership requirement can't be met that way.
This fix adds the necessary `chown` and `chmod` commands to the entry-point script.
> 2023-10-09 Mosquitto entry-point script - old-menu branch - PR 2 of 2

- .templates/mosquitto/Dockerfile
- .templates/mosquitto/docker-entrypoint.sh
Undoes some changes added by PR #521 which had the effect of preventing the health-check script from running as intended.
Detailed explanation at
[Issue 731](https://github.com/SensorsIot/IOTstack/issues/731#issuecomment-1752898143)
> 2023-10-09 Mosquitto Dockerfile - old-menu branch - PR 2 of 2

- .templates/mjpg-streamer/Dockerfile
- .templates/mjpg-streamer/docker-entrypoint.sh
- .templates/mjpg-streamer/service.yml
- docs/Containers/MJPEG-Streamer.md
Adds `mjpg-streamer` service definition and documentation. The container is designed to work with MotionEye. It provides a way to connect both "ribbon" and USB-connected web cams. From the perspective of MotionEye, all cameras are "networked" and accessed via HTTP. Streamer containers can be running on the same or different hosts as MotionEye. While the most common home arrangement is likely to be a single MotionEye instance taking feeds from multiple streamers, there can also be many-to-many relationships between streamer containers and MotionEye containers.
> 2023-10-24 mjpg-streamer container - master branch - PR 1 of 2

- .templates/mjpg-streamer/Dockerfile
- .templates/mjpg-streamer/docker-entrypoint.sh
- .templates/mjpg-streamer/service.yml
- menu.sh
Adds `mjpg-streamer` service definition. The container is designed to work with MotionEye. It provides a way to connect both "ribbon" and USB-connected web cams. From the perspective of MotionEye, all cameras are "networked" and accessed via HTTP. Streamer containers can be running on the same or different hosts as MotionEye. While the most common home arrangement is likely to be a single MotionEye instance taking feeds from multiple streamers, there can also be many-to-many relationships between streamer containers and MotionEye containers.
Documentation added to master branch.
> 2023-10-24 mjpg-streamer container - old-menu branch - PR 2 of 2

- .templates/nextcloud/service.yml
Adds TZ to NextCloud (which now seems to support timezones).
Adds port mapping 9343:443 to reserve 9343 for HTTPS access in the IOTstack context.
Makes NextCloud_DB container's TZ variable conform with current syntax.
Numerous behavioural changes are apparent in current versions of NextCloud. In particular, these problems seem to have gone away:
1. Mal-formed URLs and the requirement to pick an access method and stick to it during setup.
2. The "Access through untrusted domains" issue.
3. Dislike of being reached via a a URL containing a DNS alias (CNAME) record.
Appropriate changes to the documentation will be pushed to #737 shortly.
> 2023-10-26 NextCloud - master branch - PR 1 of 2

- .templates/nextcloud/service.yml
Adds TZ to NextCloud (which now seems to support timezones).
Adds port mapping 9343:443 to reserve 9343 for HTTPS access in the IOTstack context.
Makes NextCloud_DB container's TZ variable conform with current syntax.
> 2023-10-26 NextCloud - old-menu branch - PR 2 of 2

- scripts/docker_commands.py
The following [post](https://discord.com/channels/638610460567928832/638610461109256194/1168202784831709324) appeared on Discord:
```
Hi!
I have been using iotstack for a couple years successfully. Thanks for
this 🙂 Yesterday after doing an "update all containers", I found that
the homeassistant websocket was not installed in node-RED. I tried
removing it in the container options and installing it in node red
afterwards, and then got this error. Can it be true that node-RED is
not up to date anymore? Can I fix this with iotstack menu?
2023-10-29T14:51:12.235Z [err] ERR! notsup Unsupported engine for node-red-contrib-home-assistant-websocket@0.57.4: wanted: {"node":">=14.0.0"} (current: {"node":"12.22.8","npm":"6.14.15"})
```
This is an extract of the relevant function:
```
$ grep -A 16 …
```
> 2023-10-30 updateAllContainers() function is wrong

- install.sh
One of the most surprising things about #729 (at least to me) was how it implied that someone had actually used the `install.sh` script.
I say this with the utmost respect for the original author and subsequent contributors (who did all the work while I just sat on my hands) but, after studying the existing script, I reached the conclusion that the wisest course of action was to start from scratch. There were seemed to be so many issues in the existing `install.sh` that it was difficult to know how much could be salvaged:
* It creates `.new_install` in the current working directory (typically `~`) **before** cloning IOTstack. The menu, of course, expects that file to be in `~/IOTstack` so the menu thinks no installation work has been done.
* It (correctly) uses the "convenience script" to …
> 2023-10-24 replacement for install.sh script - master branch

- .templates/heimdall/service.yml
- docs/Containers/Heimdall.md
Issue #751 reports external port 8880 is used for both Heimdall and Zigbee2MQTT_Assistant. This PR changes the port to 8882:
```
$ git -C ~/IOTstack/.templates grep 8880
heimdall/service.yml:    - 8880:80
zigbee2mqtt_assistant/service.yml:    - "8880:80"
zigbee2mqtt_assistant/service.yml:    - VIRTUAL_PORT=8880
$ git -C ~/IOTstack/.templates grep 8882
$
```
Using port 8882 for HTTP also conveniently aligns with the second Heimdall port-mapping of `8883:443`.
Also takes the opportunity to adopt up-to-date syntax for `TZ=`.
Fixes #751
> 2024-02-14 Heimdall port conflict - master branch - PR 1 of 2

- .templates/heimdall/service.yml
- docs/Containers/Heimdall.md
Issue #751 reports external port 8880 is used for both Heimdall and Zigbee2MQTT_Assistant. This PR changes the port to 8882:
```
$ git -C ~/IOTstack/.templates grep 8880
heimdall/service.yml:    - 8880:80
zigbee2mqtt_assistant/service.yml:    - "8880:80"
zigbee2mqtt_assistant/service.yml:    - VIRTUAL_PORT=8880
$ git -C ~/IOTstack/.templates grep 8882
$
```
Using port 8882 for HTTP also conveniently aligns with the second Heimdall mapping of `8883:443`.
Old-menu documentation reduced to a stub pointing to the Wiki.
> 2024-02-14 Heimdall port conflict - old-menu branch - PR 2 of 2

- docs/Basic_setup/Troubleshooting.md
- docs/Basic_setup/index.md
- docs/Containers/Telegraf.md
- install.sh
The installer script checks for `/boot/cmdline.txt`, assumes its presence implies the Raspberry Pi and proceeds to add options to it (to support `docker stats`). With Bookworm, `/boot/cmdline.txt` is a read-me and the actual boot options file is at `/boot/firmware/cmdline.txt`.
This mod checks for the latter first, then falls back to checking for the former.
> 2024-04-24 install script - master branch

- .templates/domoticz/service.yml
Updates service definition:
- Change image to `domoticz/domoticz:stable`
- Adopt IOTstack convention for `TZ=`
- Support [documented](https://hub.docker.com/r/domoticz/domoticz) environment variables
- Remove mapping for port 6144 (no longer in use)
- Change internal TLS port to 443
- Remove redundant `data` subdirectory from left hand side of volume mapping
- Adopt new image's convention for right hand side of volume mapping
> 2024-04-23 Domoticz - old-menu branch - PR 2 of 2

- .templates/domoticz/service.yml
- docs/Containers/Domoticz.md
Updates service definition:
- Change image to `domoticz/domoticz:stable`
- Adopt IOTstack convention for `TZ=`
- Support [documented](https://hub.docker.com/r/domoticz/domoticz) environment variables
- Remove mapping for port 6144 (no longer in use)
- Change internal TLS port to 443
- Remove redundant `data` subdirectory from left hand side of volume mapping
- Adopt new image's convention for right hand side of volume mapping
Adds some documentation centred on these changes.
> 2024-04-23 Domoticz - master branch - PR 1 of 2

- .templates/dashmachine/service.yml
- .templates/heimdall/service.yml
Following on from discussion in #761, this adds quotes to port mappings as recommended in docker-compose
[documentation](https://docs.docker.com/compose/compose-file/05-services/#short-syntax-3):
> HOST:CONTAINER should always be specified as a (quoted) string, to avoid conflicts with [yaml base-60 float](https://yaml.org/type/float.html)
> 2024-04-02 missing port-mapping quotes - master branch - PR 1 of 2

- .templates/wordpress/service.yml
- menu.sh
A question on [Discord](https://discord.com/channels/638610460567928832/638610461109256194/1214646183754997801) asked whether WordPress could be added to IOTstack.
This PR is aimed at satisfying that request.
Basic documentation on master branch.
> 2024-03-28 Adds WordPress - old-menu branch - PR 2 of 2

- menu.sh
From and including `docker-compose-plugin` v2.25.0, the `version:` clause is deprecated. Commands now produce the following warning:
```
WARN[0000] /home/pi/IOTstack/docker-compose.yml: `version` is obsolete
```
This PR removes from the menu, the lines of code involved in generating the `version:` clause.
Most users will likely need to hand-edit their compose files to remove the clause.
> 2024-03-24 docker-compose.yml - old-menu branch - PR 2 of 2

- .templates/nodered/build.sh
Harmonises list of add-on nodes across old-menu and master branches. This includes removal of `node-red-node-rbe` which has been replaced by the built-in Filter node. See:
- [Release notes](https://nodered.org/blog/2021/07/20/version-2-0-released#renamed-rbe-node-to-filter-node)
Migrate from `node-red-contrib-themes/midnight-red` (deprecated) to `@node-red-contrib-themes/theme-collection` which supports many more themes. See:
- [Node-RED themes list](https://github.com/node-red-contrib-themes/theme-collection#theme-list)
Modify Dockerfile template:
1. No need to declare `EXTRA_PACKAGES` as an environment variable. It isn't needed in the container. The `ARG` reference is sufficient.
2. Remove redundant `apk update` command. The `--no-cache` flag on the `apk add` handles both package-list …
> 2024-07-30 Node-RED - old-menu branch - PR 2 of 2

- docs/Containers/Node-RED.md
1. Adds explanation of how to migrate to Debian-based Node-RED container (this follows on from a Discord question).
2. More consistent usage of reference markers defined in section on how the container gets built.
3. Rewrites section on base/local images to reflect current behaviour of `docker-compose`, and also adds pointers to build/rebuild commands.
4. Adds `-f` to `prune` commands.
5. Removes extraneous ASCII tabs that had crept in.
> 2024-07-13 Node-RED documentation - master branch

- docs/Containers/ZeroTier.md
Clarifies:
1. That enabling managed default route propagation on iOS persists until explicitly turned off.
2. That the subnets recommended for IOTstack's internal networks are private to the host and can safely be re-used across multiple IOTstack instances.
> 2024-05-17 ZeroTier documentation - master branch

- docs/Containers/Zigbee2MQTT.md
I keep fielding questions on Discord which suggest IOTstack's Zigbee2MQTT documentation doesn't place sufficient emphasis on using environment variables to pass configuration settings to the container.
Also, the advent of adapters which are reachable via TCP isn't mentioned so I have included an example.
Opportunistic cleanup of spurious 0x090A sequences.
> 2024-12-09 Zigbee2MQTT doc - master branch

- install.sh
This PR follows on from discussion in #651 at
[@6ffm70](https://github.com/SensorsIot/IOTstack/issues/651#issuecomment-2524083300) post and later.
Previously, the `backups` and `services` folders were only created if the `~/IOTstack` folder had just been cloned.
As well as "installing", the install script should also function as a "repair" script so it is preferable to always create the `backups` and `services` directories and ensure that they, and their contents, have correct ownership.
> 2024-12-09 install.sh - master branch

- .templates/chronograf/Dockerfile
- .templates/chronograf/entrypoint.sh
- .templates/chronograf/service.yml
[PR 781](https://github.com/influxdata/influxdata-docker/pull/781) was submitted on 2025-01-21 but is has now been over 40 days without any response. It isn't clear whether it is simply taking the time it needs to take, or if this is a signal that it will never be processed.
The basic problem occurs with Docker "bind mounts" which are the convention for IOTstack containers. If Chronograf launches from a clean slate, Docker will create `./volumes/chronograf` with root ownership. Although the container *launches* as root, it does not take the opportunity to enforce its ownership conventions prior to downgrading its privileges to that of (internal) user `chronograf` (ID=999). The result is the container can't write to its persistent store, crashes and goes into a restart loop.
This PR …
> 2025-03-05 Chronograf - old-menu branch - PR 2 of 2

- .templates/chronograf/Dockerfile
- .templates/chronograf/entrypoint.sh
- .templates/chronograf/service.yml
- docs/Containers/Chronograf.md
[PR 781](https://github.com/influxdata/influxdata-docker/pull/781) was submitted on 2025-01-21 but is has now been over 40 days without any response. It isn't clear whether it is simply taking the time it needs to take, or if this is a signal that it will never be processed.
The basic problem occurs with Docker "bind mounts" which are the convention for IOTstack containers. If Chronograf launches from a clean slate, Docker will create `./volumes/chronograf` with root ownership. Although the container *launches* as root, it does not take the opportunity to enforce its ownership conventions prior to downgrading its privileges to that of (internal) user `chronograf` (ID=999). The result is the container can't write to its persistent store, crashes and goes into a restart loop.
This PR …
> 2025-03-05 Chronograf - master branch - PR 1 of 2

- .templates/gitea/gitea.env
- .templates/gitea/service.yml
1. Updates to image which is being actively maintained.
2. Adopts environment variable conventions of new image.
3. Uses custom MariaDB instance as back-end.
4. Removes `/etc/timezone` mapping (without replacing with `TZ`) because new image is built without `tzdata`.
5. Empty `gitea.env` removed in favour of inline environment variables.
6. Basic documentation on master branch.
> 2025-04-24 gitea - old-menu branch - PR 2 of 2

- .templates/gitea/service.yml
- docs/Containers/Gitea.md
1. Updates to image which is being actively maintained.
2. Adopts environment variable conventions of new image.
3. Uses custom MariaDB instance as back-end.
4. Removes `/etc/timezone` mapping (without replacing with `TZ`) because new image is built without `tzdata`.
5. Adds basic documentation.
> 2025-04-24 gitea - master branch - PR 1 of 2

- .templates/mariadb/Dockerfile
- .templates/mariadb/iotstack_healthcheck.sh
1. Dockerfile syntax deprecates `ENV key value` in favour of `ENV key=value`.
2. Adjust health-check script to deal with two problems:
a. An issue where `MYSQL_ROOT_PASSWORD` does not result in a root
password being set on a newly-initialised database.
See [docker-mariadb issue 163](https://github.com/linuxserver/docker-mariadb/issues/163)
b. Steady deprecation of `mysqladmin` in favour of `mariadb-admin`.
> 2025-04-24 mariadb - master branch - PR 1 of 2

- docs/Containers/Pi-hole.md
A DM on the IOTstack Discord channel pointed out that the Pi-hole documentation did not explain how to alter the resolver configuration in the presence of NetworkManager.
This PR adds the necessary instructions.
Takes the opportunity to move the focus away from an assumption of a Raspberry Pi (and discussions of Bullseye-and-earlier vs Bookworm; or Raspberry Pi OS vs Debian) by adopting the term "Pi-hole system" as meaning "The host platform where the Pi-hole service is running."
> 2025-03-16 Pi-hole - master branch

- .templates/influxdb/service.yml
- docs/Containers/InfluxDB.md
- docs/Containers/InfluxDB2.md
InfluxDB has departed from the pattern established in 2021 whereby pinning to the `1.8` tag was (effectively) a synonym for "the latest release of InfluxDB 1".
At some point in the last few months, the `1.11` tag took on this role. This seems to have happened after a period of experimentation involving variants of `1.9-xx` and `1.10-xx`. It looks like there never were plain `1.9` or `1.10` tags so we (IOTstack) really haven't missed much.
The 1.8 (and earlier) containers launched as root. The 1.11 container launches as root but downgrades its privileges to user ID 1500 (user `influxdb` inside the container). In a clean-slate situation, `docker-compose` will create the persistent store owned by root. In an "upgrade 1.8 to 1.11" situation, the persistent store will be owned by root. Version …
> 2025-04-24 influxdb - master branch - PR 1 of 2

- install.sh
- menu.sh
Changes to `install.sh`:
1. Bumps version number to 2025v01.
2. Rather than defaulting to `~/IOTstack` or requiring the `IOTSTACK` environment variable to point to the correct directory, now gives precedence to the directory where `install.sh` is running. Maintains backwards compatibility with earlier methods.
3. Adds `dialout` to groups list. This is needed for `deconz` and should probably always have been present. Equivalent PiBuilder change made.
4. Adds `version_json()` function which returns JSON structure with:
- version number (as above)
- commit ID of `install.sh`
- exit code of installer script
5. Adds `should_run_installer()` which can be invoked via:
```
$ ./install.sh should_run_installer
```
returning either "false" or "true". In essence, if `install.sh` is
updated, its …
> 2025-09-16 installer and menu improvements - master branch
