SensorsIot/IOTstack

- .templates/python/directoryfix.sh
This is from: gcgarner#143 Contributor: @kauffman-repo
> get current user in directoryfix.sh

- scripts/docker_backup.sh
fixes issue https://github.com/gcgarner/IOTstack/issues/127
This is from: gcgarner#151 Contributor: @DIYtechie
> line 61 fixed

- .templates/dozzle/service.yml
- .templates/mosquitto/mosquitto.conf
- menu.sh
Web based Realtime container log
> Feature/add dozzle container 

- .templates/deconz/build.sh
- docs/deconz.md
Felt like the wiki was missing some troubleshooting text and spotted some unnecessary echos.
The docker-compose service files are identical
> Added troubleshooting text, new menu text and minor code cleanup

- .gitignore
- .templates/nodered/build.sh
- .templates/transmission/build.sh
- .templates/transmission/service.yml
- .templates/transmission/volumes.yml
- README.md
- compose-override.yml
- menu.sh
- scripts/docker_backup.sh
- scripts/yaml_merge.py
This is testing all the new PRs before they get merged into master. I will add a CONTRIBUTING doc explain to new people that we will test PRs out in experimental, but I just created this PR for now. The other, individual PRs can be closed if you are happy with them all.
> Experimental Branch

- docs/Containers/WireGuard.md
This pull request adds the file "docs/Containers/WireGuard.md", which
describes the WireGuard container and includes instructions for
container configuration, network configuration and mobile client device setup.
> Creates documentation for WireGuard container

- docs/Containers/Home-Assistant.md
Add info on the use of wired connection when installing Home Assistant
> 20201211 hassio readme

- docs/Containers/Zigbee2MQTT.md
changed zigbe2mqtt to zigbee2mqtt
> fixed spelling mistake Zigbee2MQTT

- scripts/menu_main.py
- scripts/python_deps_check.py
Fixes for handling missing docker or PyYaml
I needed to make these changes to run menu.sh in a minimal container.
> Fixes for missing optional dependencies

- .templates/zigbee2mqtt/service.yml
- docs/Containers/Zigbee2MQTT.md
Added a config alternative for Electrolama dongles and updated container documentation
> Zigbee2mqtt update

- .templates/deconz/service.yml
References:
1. [Discord question](https://discord.com/channels/638610460567928832/638610461109256194/909831079253393419).
2. [GitHub deconz-community](https://github.com/deconz-community/deconz-docker).
Changes recommended from Reference #2:
* Image from:
- `marthoc/deconz:stable`
to:
- `deconzcommunity/deconz`
* Right hand side of volumes mapping from:
- `/root/.local/share/dresden-elektronik/deCONZ`
to:
- `/opt/deCONZ`
> 20211116 Deconz community - master branch - PR 1 of 3

- .templates/deconz/service_conbee.yml
- .templates/deconz/service_conbee_II.yml
- .templates/deconz/service_raspbee.yml
References:
1. [Discord question](https://discord.com/channels/638610460567928832/638610461109256194/909831079253393419).
2. [GitHub deconz-community](https://github.com/deconz-community/deconz-docker).
Changes recommended from Reference #2:
* Image from:
- `marthoc/deconz:stable`
to:
- `deconzcommunity/deconz`
* Right hand side of volumes mapping from:
- `/root/.local/share/dresden-elektronik/deCONZ`
to:
- `/opt/deCONZ`
Identical changes made to all three `service_xxx.yml` files.
> 20211116 Deconz community - old-menu branch - PR 2 of 3

- .internal/templates/services/deconz/template.yml
References:
1. [Discord question](https://discord.com/channels/638610460567928832/638610461109256194/909831079253393419).
2. [GitHub deconz-community](https://github.com/deconz-community/deconz-docker).
Changes recommended from Reference #2:
* Image from:
- `marthoc/deconz:stable`
to:
- `deconzcommunity/deconz`
* Right hand side of volumes mapping from:
- `/root/.local/share/dresden-elektronik/deCONZ`
to:
- `/opt/deCONZ`
> 20211116 Deconz community - experimental branch - PR 3 of 3

- .templates/domoticz/service.yml
- .templates/dozzle/service.yml
- docs/Default-Configs.md
Port 8080 is used by zigbee2mqtt
> Fix port conflicts

- .templates/home_assistant/service.yml
- docs/Containers/Home-Assistant.md
Fixes #484 by:
* updating `service.yml` for Home Assistant container
* updating associated documentation
> Enable BT & BLE in Home Assistant container

- docs/Containers/Dozzle.md
Currently planning on creating the missing docs.
This is my first ever pull request, so please lmk if I did something wrong.
> add doc for dozzle

- docs/Basic_setup/Custom.md
Result available at: https://ukkopahis.github.io/IOTstack/Basic_setup/Custom/
> docs/Custom: Add overview of compose file override options

- docs/Containers/Python.md
> 20220327 Python documentation

- .templates/syncthing/service.yml
- docs/Containers/Syncthing.md
Added syncthing service from linuxserver/syncthing:latest
Resources; .templates/syncthing/service.yml
Note. This is my first PR to the project so maybe I am missing several things to do it properly.
> add syncthing service to IOTstack

- docs/Containers/InfluxDB.md
* opening the CLI shell
* how to change configuration settings
* how to do maintenance on container refusing to start
Preview available at: https://ukkopahis.github.io/IOTstack/Containers/InfluxDB/
> docs/influxdb: configuring settings, how to fix broken container

- .internal/templates/services/influxdb2/template.yml
Adds template for InfluxDB 2 container.
Documentation on Master branch.
> 20220602 InfluxDB 2 - experimental branch - PR 3 of 3

- .templates/grafana/service.yml
- .templates/influxdb/service.yml
Adds health-check functionality to Grafana and InfluxDB 1.8, as
discussed in #415.
Health-check functionality already added to Mosquitto via #406.
Closes #415
> 20220517 Grafana InfluxDB HealthCheck - master branch - PR 1 of 3

- docs/Basic_setup/Custom.md
- docs/Basic_setup/index.md
- docs/Containers/Home-Assistant.md
* Code-block highligt fixes
* Custom overrides: some minor rewording
> Docs: fix and add missing code highlight

- docs/Containers/InfluxDB.md
Expand InfluxDB 1.8 documentation by incorporating material from:
* [Tutorial: Enabling authentication in InfluxDB](https://gist.github.com/Paraphraser/9f3aa21fddd5d4e8141a7ab03ffb4dd7)
* [Tutorial: Enabling UDP support in InfluxDB](https://gist.github.com/Paraphraser/15483641fc657a147dfae7b03d291bc0)
I thought I had already added this material but a Discord question made
me realise I was mistaken.
General tidy-up because a lot of the example material was either wrong
or out-of-date.
> 20220901 InfluxDB - master branch - documentation

- docs/Containers/NextCloud.md
Fixes some typos and updates some out-of-date information.
> 20220705 NextCloud documentation

- docs/Developers/index.md
- scripts/development/mkdocs-serve.sh
> mkdocs: script automating python virtualenv use

- scripts/buildstack_menu.py
- scripts/deps/yaml_merge.py
Fixes #433
Also improves on exception reporting to include full stacktrace, allowing easier fixing of user-reported errors.
> menu: fix error on empty compose-override.yml

- .templates/scrypted/service.yml
- docs/Containers/Scrypted.md
Adds first-cut service definition for "scrypted" to master branch.
**Only for testing at this point.**
Minimal documentation added.
Not yet added to old-menu or experimental.
> 2022-11-11 scrypted - master branch

- scripts/2022-10-01-wireguard-restructure.sh
Adds dependency checking for jq and rclone.
> 2022-12-02 Wireguard helper script - experimental branch - PR 3 of 3

- scripts/2022-10-01-wireguard-restructure.sh
Adds dependency checking for jq and rclone.
> 2022-12-02 Wireguard helper script - old-menu branch - PR 2 of 3

- scripts/2022-10-01-wireguard-restructure.sh
Adds dependency checking for jq and rclone.
> 2022-12-02 Wireguard helper script - master branch - PR 1 of 3

- .templates/heimdall/service.yml
Update heimdall's service.yml to bring it in line with the other templates in IOTstack
> Update heimdall service.yml

- docs/Containers/Pi-hole.md
Fix typo in example (182.168 should be 192.168).
> 2023-02-16 Pi-hole documentation

- .templates/portainer-ce/service.yml
> Add HTTPS Port to portainer service.

- docs/Containers/InfluxDB.md
Restructure debugging material and add instructions on using `tcpdump` to capture live traffic being sent to the container on port 8086.
> 2023-01-29 InfluxDB documentation - master branch

- .gitignore
Adds `.env` to .gitignore. Also harmonises ignore file across all three branches.
> 2023-05-15 .gitignore harmonisation - master branch - PR 1 of 3

- .gitignore
Adds `.env` to .gitignore. Also harmonises ignore file across all three branches.
> 2023-05-15 .gitignore harmonisation - old-menu branch - PR 2 of 3

- .gitignore
Adds `.env` to .gitignore. Also harmonises ignore file across all three branches.
> 2023-05-15 .gitignore harmonisation - experimental branch - PR 3 of 3

- docs/Containers/ZeroTier-vs-WireGuard.md
- docs/Containers/ZeroTier.md
Fixes grammatical issue in Zerotier-vs-WireGuard document.
Adds iOS tip to ZeroTier document.
> 2023-05-25 Zerotier documentation - master branch

- .gitignore
- scripts/backup.sh
This PR:
- adds the .idea folder to .gitignore to enable other IDEs
- adds the standard docker-compose override mechanism both to .gitignore and the backup
fixes #183
> Developer setup improvements and custom file handling

- docs/Developers/index.md
Update default configs reference in the Checks section to reflect recent changes related to the creation of the helper script.
> 20230405 Update index.md Checks section

- docs/Containers/Grafana.md
Describes new syntax for resetting the administrative password.
> 2023-06-29 Grafana

- docs/Containers/Node-RED.md
- docs/Containers/PostgreSQL.md
- docs/Containers/Telegraf.md
Fixes some minor problems:
- Node-RED
- replaces Unicode glyphs with encoding sequences (better UTF-8 compatibility)
- fixes duplicate internal link target
- PostgreSQL
- fixes mal-formed internal link target
- Telegraf
- fixes duplicate internal link target
> 2023-07-14 documentation - master branch

- install.sh
This fixes the incorrect evaluation of the installed Docker version variable.
> Fix Docker version check condition.

- docs/Containers/Node-RED.md
Expands discussion on hardware serial and Bluetooth devices. Follows on from #690 and includes more information about how to enable the devices under Bookworm.
Research triggered by comments appended to #761.
> 2024-04-02 Node-RED documentation - master branch

- .templates/wordpress/service.yml
- docs/Containers/WordPress.md
A question on [Discord](https://discord.com/channels/638610460567928832/638610461109256194/1214646183754997801) asked whether WordPress could be added to IOTstack.
This PR is aimed at satisfying that request.
Includes basic documentation.
> 2024-03-28 Adds WordPress - master branch - PR 1 of 2

- .templates/nodered/addons.yml
https://flows.nodered.org/node/@flowfuse/node-red-dashboard
> Added the new dashboard for NodeRed. Defaulted to off

- install.sh
1. Adopts recommended she-bang syntax.
2. Adds version number to banner (mainly as a visual aid when discussing installation issues on Discord).
3. Removes internal SCRIPT variable which has a dependency on whether the script is invoked directly or piped to bash.
4. No need to resolve absolute path for `IOTSTACK` variable. This just causes an error in green-fields situations.
5. Better messaging in `handle_exit()` so it is clear whether the script completed normally with no further work to do, or should be re-run.
6. Better handling of "logout required" situation. Rather than killing the immediate parent process (`$PPID`), now iterates the process ancestry to find the most-distant ancestor owned by the current user. For SSH connections this is typically the `sshd` spawned for the user. …
> 2024-08-08 installer script - master branch

- .templates/esphome/88-tty-iotstack-esphome.rules
- .templates/esphome/build.sh
- .templates/esphome/service.yml
- menu.sh
Adds ESPHome container, as requested by #754.
Documentation on master branch.
> 2024-07-21 Adds ESPHome - old-menu branch - PR 2 of 2

- docs/Containers/WireGuard.md
- docs/Containers/Zigbee2MQTT.md
- docs/Updates/Changelog.md
Fixes warnings produced by `mkdocs` about broken links.
> 2024-10-26 docs - master branch

- .templates/pihole/service.yml
https://docs.pi-hole.net/docker/upgrading/v5-v6/
> Update service.yml for Pi-hole, pinned to 2024.07.0

- .templates/adguardhome/service.yml
Updates service definition to incorporate recent changes.
Simpler layout of ports structure.
Documentation on master branch.
> 2024-09-09 AdGuard Home - old-menu branch - PR 2 of 2

- .templates/adguardhome/service.yml
- docs/Containers/AdGuardHome.md
Updates service definition to incorporate recent changes.
Simpler layout of ports structure.
Updates documentation.
> 2025-03-16 AdGuard Home - master branch - PR 1 of 2
